---
helmDefaults:
  cleanupOnFail: true
  wait: true
  waitForJobs: true
  createNamespace: false
  historyMax: 1
  timeout: 120

repositories:
  - name: bjw-s-charts
    url: https://bjw-s.github.io/helm-charts
  - name: goauthentik-charts
    url: https://charts.goauthentik.io

releases:
  - name: authentik-client-cas
    chart: bjw-s-charts/app-template
    version: 3.7.0
    atomic: true
    values:
      - ./client-cas.values.yaml
  - name: authentik-backend
    chart: bjw-s-charts/app-template
    version: 3.7.0
    atomic: true
    needs:
      - authentik-client-cas
    values:
      - ./backend.values.yaml
  - name: authentik
    chart: goauthentik-charts/authentik
    version: 2025.2.0
    # atomic: true
    timeout: 300
    needs:
      - authentik-backend
    values:
      - ./authentik.values.yaml
