// Code generated by mockery v2.53.6. DO NOT EDIT.

package barmancloud

import (
	contexts "github.com/solidDoWant/backup-tool/pkg/contexts"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/cloudnative-pg/plugin-barman-cloud/api/v1"
)

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

type MockClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInterface) EXPECT() *MockClientInterface_Expecter {
	return &MockClientInterface_Expecter{mock: &_m.Mock}
}

// GetObjectStore provides a mock function with given fields: ctx, namespace, name
func (_m *MockClientInterface) GetObjectStore(ctx *contexts.Context, namespace string, name string) (*v1.ObjectStore, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectStore")
	}

	var r0 *v1.ObjectStore
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string) (*v1.ObjectStore, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string) *v1.ObjectStore); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ObjectStore)
		}
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_GetObjectStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectStore'
type MockClientInterface_GetObjectStore_Call struct {
	*mock.Call
}

// GetObjectStore is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - name string
func (_e *MockClientInterface_Expecter) GetObjectStore(ctx interface{}, namespace interface{}, name interface{}) *MockClientInterface_GetObjectStore_Call {
	return &MockClientInterface_GetObjectStore_Call{Call: _e.mock.On("GetObjectStore", ctx, namespace, name)}
}

func (_c *MockClientInterface_GetObjectStore_Call) Run(run func(ctx *contexts.Context, namespace string, name string)) *MockClientInterface_GetObjectStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientInterface_GetObjectStore_Call) Return(_a0 *v1.ObjectStore, _a1 error) *MockClientInterface_GetObjectStore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_GetObjectStore_Call) RunAndReturn(run func(*contexts.Context, string, string) (*v1.ObjectStore, error)) *MockClientInterface_GetObjectStore_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
