// Code generated by mockery v2.53.6. DO NOT EDIT.

package clonedcluster

import (
	contexts "github.com/solidDoWant/backup-tool/pkg/contexts"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/cloudnative-pg/cloudnative-pg/api/v1"
)

// MockProviderInterface is an autogenerated mock type for the ProviderInterface type
type MockProviderInterface struct {
	mock.Mock
}

type MockProviderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderInterface) EXPECT() *MockProviderInterface_Expecter {
	return &MockProviderInterface_Expecter{mock: &_m.Mock}
}

// CloneClusterFromBackup provides a mock function with given fields: ctx, namespace, existingClusterName, newClusterName, servingCertIssuerName, clientCertIssuerName, backup, opts
func (_m *MockProviderInterface) CloneClusterFromBackup(ctx *contexts.Context, namespace string, existingClusterName string, newClusterName string, servingCertIssuerName string, clientCertIssuerName string, backup *v1.Backup, opts CloneClusterOptions) (ClonedClusterInterface, error) {
	ret := _m.Called(ctx, namespace, existingClusterName, newClusterName, servingCertIssuerName, clientCertIssuerName, backup, opts)

	if len(ret) == 0 {
		panic("no return value specified for CloneClusterFromBackup")
	}

	var r0 ClonedClusterInterface
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, string, string, string, *v1.Backup, CloneClusterOptions) (ClonedClusterInterface, error)); ok {
		return rf(ctx, namespace, existingClusterName, newClusterName, servingCertIssuerName, clientCertIssuerName, backup, opts)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, string, string, string, *v1.Backup, CloneClusterOptions) ClonedClusterInterface); ok {
		r0 = rf(ctx, namespace, existingClusterName, newClusterName, servingCertIssuerName, clientCertIssuerName, backup, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ClonedClusterInterface)
		}
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context, string, string, string, string, string, *v1.Backup, CloneClusterOptions) error); ok {
		r1 = rf(ctx, namespace, existingClusterName, newClusterName, servingCertIssuerName, clientCertIssuerName, backup, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderInterface_CloneClusterFromBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloneClusterFromBackup'
type MockProviderInterface_CloneClusterFromBackup_Call struct {
	*mock.Call
}

// CloneClusterFromBackup is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - existingClusterName string
//   - newClusterName string
//   - servingCertIssuerName string
//   - clientCertIssuerName string
//   - backup *v1.Backup
//   - opts CloneClusterOptions
func (_e *MockProviderInterface_Expecter) CloneClusterFromBackup(ctx interface{}, namespace interface{}, existingClusterName interface{}, newClusterName interface{}, servingCertIssuerName interface{}, clientCertIssuerName interface{}, backup interface{}, opts interface{}) *MockProviderInterface_CloneClusterFromBackup_Call {
	return &MockProviderInterface_CloneClusterFromBackup_Call{Call: _e.mock.On("CloneClusterFromBackup", ctx, namespace, existingClusterName, newClusterName, servingCertIssuerName, clientCertIssuerName, backup, opts)}
}

func (_c *MockProviderInterface_CloneClusterFromBackup_Call) Run(run func(ctx *contexts.Context, namespace string, existingClusterName string, newClusterName string, servingCertIssuerName string, clientCertIssuerName string, backup *v1.Backup, opts CloneClusterOptions)) *MockProviderInterface_CloneClusterFromBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(*v1.Backup), args[7].(CloneClusterOptions))
	})
	return _c
}

func (_c *MockProviderInterface_CloneClusterFromBackup_Call) Return(cluster ClonedClusterInterface, err error) *MockProviderInterface_CloneClusterFromBackup_Call {
	_c.Call.Return(cluster, err)
	return _c
}

func (_c *MockProviderInterface_CloneClusterFromBackup_Call) RunAndReturn(run func(*contexts.Context, string, string, string, string, string, *v1.Backup, CloneClusterOptions) (ClonedClusterInterface, error)) *MockProviderInterface_CloneClusterFromBackup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateClusterBackup provides a mock function with given fields: ctx, namespace, existingClusterName, opts
func (_m *MockProviderInterface) CreateClusterBackup(ctx *contexts.Context, namespace string, existingClusterName string, opts CloneClusterOptions) (*v1.Backup, error) {
	ret := _m.Called(ctx, namespace, existingClusterName, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateClusterBackup")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, CloneClusterOptions) (*v1.Backup, error)); ok {
		return rf(ctx, namespace, existingClusterName, opts)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, CloneClusterOptions) *v1.Backup); ok {
		r0 = rf(ctx, namespace, existingClusterName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context, string, string, CloneClusterOptions) error); ok {
		r1 = rf(ctx, namespace, existingClusterName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderInterface_CreateClusterBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClusterBackup'
type MockProviderInterface_CreateClusterBackup_Call struct {
	*mock.Call
}

// CreateClusterBackup is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - existingClusterName string
//   - opts CloneClusterOptions
func (_e *MockProviderInterface_Expecter) CreateClusterBackup(ctx interface{}, namespace interface{}, existingClusterName interface{}, opts interface{}) *MockProviderInterface_CreateClusterBackup_Call {
	return &MockProviderInterface_CreateClusterBackup_Call{Call: _e.mock.On("CreateClusterBackup", ctx, namespace, existingClusterName, opts)}
}

func (_c *MockProviderInterface_CreateClusterBackup_Call) Run(run func(ctx *contexts.Context, namespace string, existingClusterName string, opts CloneClusterOptions)) *MockProviderInterface_CreateClusterBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string), args[3].(CloneClusterOptions))
	})
	return _c
}

func (_c *MockProviderInterface_CreateClusterBackup_Call) Return(_a0 *v1.Backup, _a1 error) *MockProviderInterface_CreateClusterBackup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderInterface_CreateClusterBackup_Call) RunAndReturn(run func(*contexts.Context, string, string, CloneClusterOptions) (*v1.Backup, error)) *MockProviderInterface_CreateClusterBackup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProviderInterface creates a new instance of MockProviderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderInterface {
	mock := &MockProviderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
