filename: "{{ .InterfaceName | lower }}_mock.go"
dir: "{{ .InterfaceDir }}"
inpackage: true
packages:
  github.com/solidDoWant/backup-tool/cmd/disasterrecovery: &baseline_config
    config:
      issue-845-fix: true
      resolve-type-alias: false
    interfaces:
      DREventCommand:
      DREventGenerateSchemaCommand:
      DRCommand:
      DRBackupCommand:
      DRRestoreCommand:
  github.com/solidDoWant/backup-tool/pkg/cli/features:
    <<: *baseline_config
    interfaces:
      ConfigFileCommandInterface:
      ContextCommandInterface:
      KubeClusterCommandInterface:
      KubernetesCommandInterface:
  github.com/solidDoWant/backup-tool/pkg/disasterrecovery/actions/remote:
    <<: *baseline_config
    interfaces:
      RemoteStageInterface:
      RemoteAction:
      CleanupAction:
  ? github.com/solidDoWant/backup-tool/pkg/disasterrecovery/actions/remote/cnpg/restore
  : <<: *baseline_config
    interfaces:
      CNPGRestoreInterface:
  github.com/solidDoWant/backup-tool/pkg/disasterrecovery/actions/remote/s3sync:
    <<: *baseline_config
    interfaces:
      S3SyncInterface:
  github.com/solidDoWant/backup-tool/pkg/files:
    <<: *baseline_config
    interfaces:
      Runtime:
  github.com/solidDoWant/backup-tool/pkg/grpc/clients:
    <<: *baseline_config
    interfaces:
      ClientInterface:
  github.com/solidDoWant/backup-tool/pkg/kubecluster/helpers:
    <<: *baseline_config
    interfaces:
      metaResource:
      ListerWatcher:
  github.com/solidDoWant/backup-tool/pkg/kubecluster:
    <<: *baseline_config
    interfaces:
      ClientInterface:
  ? github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/backuptoolinstance
  : &kube_composite_config
    <<: *baseline_config
    interfaces:
      ProviderInterface:
      BackupToolInstanceInterface:
  ? github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/createcrpforcertificate
  : <<: *baseline_config
    interfaces:
      ProviderInterface:
  github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/clusterusercert:
    <<: *baseline_config
    interfaces:
      ProviderInterface:
      ClusterUserCertInterface:
  github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/clonepvc: *kube_composite_config
  github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/clonedcluster:
    <<: *baseline_config
    interfaces:
      ProviderInterface:
      ClonedClusterInterface:
  github.com/solidDoWant/backup-tool/pkg/kubecluster/primatives/approverpolicy:
    &kube_primative_config
    <<: *baseline_config
    interfaces:
      ClientInterface:
  github.com/solidDoWant/backup-tool/pkg/kubecluster/primatives/certmanager: *kube_primative_config
  github.com/solidDoWant/backup-tool/pkg/kubecluster/primatives/cnpg: *kube_primative_config
  github.com/solidDoWant/backup-tool/pkg/kubecluster/primatives/externalsnapshotter: *kube_primative_config
  github.com/solidDoWant/backup-tool/pkg/kubecluster/primatives/core: *kube_primative_config
  github.com/solidDoWant/backup-tool/pkg/postgres:
    <<: *baseline_config
    interfaces:
      Runtime:
  github.com/solidDoWant/backup-tool/pkg/s3:
    <<: *baseline_config
    interfaces:
      CredentialsInterface:
      Runtime:
      syncManager:
