// Code generated by mockery v2.51.0. DO NOT EDIT.

package restore

import (
	clients "github.com/solidDoWant/backup-tool/pkg/grpc/clients"
	backuptoolinstance "github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/backuptoolinstance"

	contexts "github.com/solidDoWant/backup-tool/pkg/contexts"

	kubecluster "github.com/solidDoWant/backup-tool/pkg/kubecluster"

	mock "github.com/stretchr/testify/mock"
)

// MockCNPGRestoreInterface is an autogenerated mock type for the CNPGRestoreInterface type
type MockCNPGRestoreInterface struct {
	mock.Mock
}

type MockCNPGRestoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCNPGRestoreInterface) EXPECT() *MockCNPGRestoreInterface_Expecter {
	return &MockCNPGRestoreInterface_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with given fields: ctx
func (_m *MockCNPGRestoreInterface) Cleanup(ctx *contexts.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCNPGRestoreInterface_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockCNPGRestoreInterface_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockCNPGRestoreInterface_Expecter) Cleanup(ctx interface{}) *MockCNPGRestoreInterface_Cleanup_Call {
	return &MockCNPGRestoreInterface_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx)}
}

func (_c *MockCNPGRestoreInterface_Cleanup_Call) Run(run func(ctx *contexts.Context)) *MockCNPGRestoreInterface_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockCNPGRestoreInterface_Cleanup_Call) Return(_a0 error) *MockCNPGRestoreInterface_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCNPGRestoreInterface_Cleanup_Call) RunAndReturn(run func(*contexts.Context) error) *MockCNPGRestoreInterface_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Configure provides a mock function with given fields: kubeClusterClient, namespace, clusterName, servingCertName, clientCertIssuerName, drVolName, backupFileRelPath, opts
func (_m *MockCNPGRestoreInterface) Configure(kubeClusterClient kubecluster.ClientInterface, namespace string, clusterName string, servingCertName string, clientCertIssuerName string, drVolName string, backupFileRelPath string, opts CNPGRestoreOptions) error {
	ret := _m.Called(kubeClusterClient, namespace, clusterName, servingCertName, clientCertIssuerName, drVolName, backupFileRelPath, opts)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(kubecluster.ClientInterface, string, string, string, string, string, string, CNPGRestoreOptions) error); ok {
		r0 = rf(kubeClusterClient, namespace, clusterName, servingCertName, clientCertIssuerName, drVolName, backupFileRelPath, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCNPGRestoreInterface_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockCNPGRestoreInterface_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - kubeClusterClient kubecluster.ClientInterface
//   - namespace string
//   - clusterName string
//   - servingCertName string
//   - clientCertIssuerName string
//   - drVolName string
//   - backupFileRelPath string
//   - opts CNPGRestoreOptions
func (_e *MockCNPGRestoreInterface_Expecter) Configure(kubeClusterClient interface{}, namespace interface{}, clusterName interface{}, servingCertName interface{}, clientCertIssuerName interface{}, drVolName interface{}, backupFileRelPath interface{}, opts interface{}) *MockCNPGRestoreInterface_Configure_Call {
	return &MockCNPGRestoreInterface_Configure_Call{Call: _e.mock.On("Configure", kubeClusterClient, namespace, clusterName, servingCertName, clientCertIssuerName, drVolName, backupFileRelPath, opts)}
}

func (_c *MockCNPGRestoreInterface_Configure_Call) Run(run func(kubeClusterClient kubecluster.ClientInterface, namespace string, clusterName string, servingCertName string, clientCertIssuerName string, drVolName string, backupFileRelPath string, opts CNPGRestoreOptions)) *MockCNPGRestoreInterface_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(kubecluster.ClientInterface), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string), args[7].(CNPGRestoreOptions))
	})
	return _c
}

func (_c *MockCNPGRestoreInterface_Configure_Call) Return(_a0 error) *MockCNPGRestoreInterface_Configure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCNPGRestoreInterface_Configure_Call) RunAndReturn(run func(kubecluster.ClientInterface, string, string, string, string, string, string, CNPGRestoreOptions) error) *MockCNPGRestoreInterface_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: ctx, backupToolClient
func (_m *MockCNPGRestoreInterface) Execute(ctx *contexts.Context, backupToolClient clients.ClientInterface) error {
	ret := _m.Called(ctx, backupToolClient)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, clients.ClientInterface) error); ok {
		r0 = rf(ctx, backupToolClient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCNPGRestoreInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCNPGRestoreInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - backupToolClient clients.ClientInterface
func (_e *MockCNPGRestoreInterface_Expecter) Execute(ctx interface{}, backupToolClient interface{}) *MockCNPGRestoreInterface_Execute_Call {
	return &MockCNPGRestoreInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, backupToolClient)}
}

func (_c *MockCNPGRestoreInterface_Execute_Call) Run(run func(ctx *contexts.Context, backupToolClient clients.ClientInterface)) *MockCNPGRestoreInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(clients.ClientInterface))
	})
	return _c
}

func (_c *MockCNPGRestoreInterface_Execute_Call) Return(_a0 error) *MockCNPGRestoreInterface_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCNPGRestoreInterface_Execute_Call) RunAndReturn(run func(*contexts.Context, clients.ClientInterface) error) *MockCNPGRestoreInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Setup provides a mock function with given fields: ctx, btiOpts
func (_m *MockCNPGRestoreInterface) Setup(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions) error {
	ret := _m.Called(ctx, btiOpts)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error); ok {
		r0 = rf(ctx, btiOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCNPGRestoreInterface_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockCNPGRestoreInterface_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions
func (_e *MockCNPGRestoreInterface_Expecter) Setup(ctx interface{}, btiOpts interface{}) *MockCNPGRestoreInterface_Setup_Call {
	return &MockCNPGRestoreInterface_Setup_Call{Call: _e.mock.On("Setup", ctx, btiOpts)}
}

func (_c *MockCNPGRestoreInterface_Setup_Call) Run(run func(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions)) *MockCNPGRestoreInterface_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(*backuptoolinstance.CreateBackupToolInstanceOptions))
	})
	return _c
}

func (_c *MockCNPGRestoreInterface_Setup_Call) Return(_a0 error) *MockCNPGRestoreInterface_Setup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCNPGRestoreInterface_Setup_Call) RunAndReturn(run func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error) *MockCNPGRestoreInterface_Setup_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: ctx
func (_m *MockCNPGRestoreInterface) Validate(ctx *contexts.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCNPGRestoreInterface_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockCNPGRestoreInterface_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockCNPGRestoreInterface_Expecter) Validate(ctx interface{}) *MockCNPGRestoreInterface_Validate_Call {
	return &MockCNPGRestoreInterface_Validate_Call{Call: _e.mock.On("Validate", ctx)}
}

func (_c *MockCNPGRestoreInterface_Validate_Call) Run(run func(ctx *contexts.Context)) *MockCNPGRestoreInterface_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockCNPGRestoreInterface_Validate_Call) Return(_a0 error) *MockCNPGRestoreInterface_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCNPGRestoreInterface_Validate_Call) RunAndReturn(run func(*contexts.Context) error) *MockCNPGRestoreInterface_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCNPGRestoreInterface creates a new instance of MockCNPGRestoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCNPGRestoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCNPGRestoreInterface {
	mock := &MockCNPGRestoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
