---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.1/charts/library/common/values.schema.json
rawResources:
  postgres-client-ca-cert:
    forceRename: postgres-client-ca-cert
    manifest:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      spec:
        commonName: VaultWarden Postgres client CA
        isCA: true
        usages:
          - cert sign
        secretTemplate:
          labels:
            cnpg.io/reload: "true"
        issuerRef:
          name: self-signed
          kind: Issuer
          group: cert-manager.io
        secretName: postgres-client-ca-cert
  postgres-auth-ca-issuer:
    forceRename: postgres-auth-ca-issuer
    manifest:
      apiVersion: cert-manager.io/v1
      kind: Issuer
      spec:
        ca:
          secretName: postgres-client-ca-cert
  # This must be deployed prior to any certs, or whether cert requests
  # get approved or denied is racey
  postgres-auth-ca-request-policy:
    forceRename: postgres-auth-ca-request-policy
    manifest:
      apiVersion: policy.cert-manager.io/v1alpha1
      kind: CertificateRequestPolicy
      spec:
        selector:
          issuerRef:
            group: cert-manager.io
            kind: Issuer
            name: postgres-auth-ca-issuer
        allowed:
          commonName:
            required: true
            value: "*"
          usages:
            - client auth
