// Code generated by mockery v2.53.6. DO NOT EDIT.

package groupbackup

import (
	clients "github.com/solidDoWant/backup-tool/pkg/grpc/clients"
	backuptoolinstance "github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/backuptoolinstance"

	contexts "github.com/solidDoWant/backup-tool/pkg/contexts"

	kubecluster "github.com/solidDoWant/backup-tool/pkg/kubecluster"

	mock "github.com/stretchr/testify/mock"

	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MockFilesGroupBackupInterface is an autogenerated mock type for the FilesGroupBackupInterface type
type MockFilesGroupBackupInterface struct {
	mock.Mock
}

type MockFilesGroupBackupInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilesGroupBackupInterface) EXPECT() *MockFilesGroupBackupInterface_Expecter {
	return &MockFilesGroupBackupInterface_Expecter{mock: &_m.Mock}
}

// BeforeConsistencyPoint provides a mock function with given fields: ctx
func (_m *MockFilesGroupBackupInterface) BeforeConsistencyPoint(ctx *contexts.Context) (time.Time, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeforeConsistencyPoint")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) (time.Time, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context) time.Time); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFilesGroupBackupInterface_BeforeConsistencyPoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeforeConsistencyPoint'
type MockFilesGroupBackupInterface_BeforeConsistencyPoint_Call struct {
	*mock.Call
}

// BeforeConsistencyPoint is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockFilesGroupBackupInterface_Expecter) BeforeConsistencyPoint(ctx interface{}) *MockFilesGroupBackupInterface_BeforeConsistencyPoint_Call {
	return &MockFilesGroupBackupInterface_BeforeConsistencyPoint_Call{Call: _e.mock.On("BeforeConsistencyPoint", ctx)}
}

func (_c *MockFilesGroupBackupInterface_BeforeConsistencyPoint_Call) Run(run func(ctx *contexts.Context)) *MockFilesGroupBackupInterface_BeforeConsistencyPoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockFilesGroupBackupInterface_BeforeConsistencyPoint_Call) Return(_a0 time.Time, _a1 error) *MockFilesGroupBackupInterface_BeforeConsistencyPoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFilesGroupBackupInterface_BeforeConsistencyPoint_Call) RunAndReturn(run func(*contexts.Context) (time.Time, error)) *MockFilesGroupBackupInterface_BeforeConsistencyPoint_Call {
	_c.Call.Return(run)
	return _c
}

// Cleanup provides a mock function with given fields: ctx
func (_m *MockFilesGroupBackupInterface) Cleanup(ctx *contexts.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesGroupBackupInterface_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockFilesGroupBackupInterface_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockFilesGroupBackupInterface_Expecter) Cleanup(ctx interface{}) *MockFilesGroupBackupInterface_Cleanup_Call {
	return &MockFilesGroupBackupInterface_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx)}
}

func (_c *MockFilesGroupBackupInterface_Cleanup_Call) Run(run func(ctx *contexts.Context)) *MockFilesGroupBackupInterface_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockFilesGroupBackupInterface_Cleanup_Call) Return(_a0 error) *MockFilesGroupBackupInterface_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesGroupBackupInterface_Cleanup_Call) RunAndReturn(run func(*contexts.Context) error) *MockFilesGroupBackupInterface_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Configure provides a mock function with given fields: kubeClusterClient, namespace, selector, drVolName, groupName, opts
func (_m *MockFilesGroupBackupInterface) Configure(kubeClusterClient kubecluster.ClientInterface, namespace string, selector v1.LabelSelector, drVolName string, groupName string, opts FilesGroupBackupOptions) error {
	ret := _m.Called(kubeClusterClient, namespace, selector, drVolName, groupName, opts)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(kubecluster.ClientInterface, string, v1.LabelSelector, string, string, FilesGroupBackupOptions) error); ok {
		r0 = rf(kubeClusterClient, namespace, selector, drVolName, groupName, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesGroupBackupInterface_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockFilesGroupBackupInterface_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - kubeClusterClient kubecluster.ClientInterface
//   - namespace string
//   - selector v1.LabelSelector
//   - drVolName string
//   - groupName string
//   - opts FilesGroupBackupOptions
func (_e *MockFilesGroupBackupInterface_Expecter) Configure(kubeClusterClient interface{}, namespace interface{}, selector interface{}, drVolName interface{}, groupName interface{}, opts interface{}) *MockFilesGroupBackupInterface_Configure_Call {
	return &MockFilesGroupBackupInterface_Configure_Call{Call: _e.mock.On("Configure", kubeClusterClient, namespace, selector, drVolName, groupName, opts)}
}

func (_c *MockFilesGroupBackupInterface_Configure_Call) Run(run func(kubeClusterClient kubecluster.ClientInterface, namespace string, selector v1.LabelSelector, drVolName string, groupName string, opts FilesGroupBackupOptions)) *MockFilesGroupBackupInterface_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(kubecluster.ClientInterface), args[1].(string), args[2].(v1.LabelSelector), args[3].(string), args[4].(string), args[5].(FilesGroupBackupOptions))
	})
	return _c
}

func (_c *MockFilesGroupBackupInterface_Configure_Call) Return(_a0 error) *MockFilesGroupBackupInterface_Configure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesGroupBackupInterface_Configure_Call) RunAndReturn(run func(kubecluster.ClientInterface, string, v1.LabelSelector, string, string, FilesGroupBackupOptions) error) *MockFilesGroupBackupInterface_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: ctx, backupToolClient
func (_m *MockFilesGroupBackupInterface) Execute(ctx *contexts.Context, backupToolClient clients.ClientInterface) error {
	ret := _m.Called(ctx, backupToolClient)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, clients.ClientInterface) error); ok {
		r0 = rf(ctx, backupToolClient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesGroupBackupInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFilesGroupBackupInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - backupToolClient clients.ClientInterface
func (_e *MockFilesGroupBackupInterface_Expecter) Execute(ctx interface{}, backupToolClient interface{}) *MockFilesGroupBackupInterface_Execute_Call {
	return &MockFilesGroupBackupInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, backupToolClient)}
}

func (_c *MockFilesGroupBackupInterface_Execute_Call) Run(run func(ctx *contexts.Context, backupToolClient clients.ClientInterface)) *MockFilesGroupBackupInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(clients.ClientInterface))
	})
	return _c
}

func (_c *MockFilesGroupBackupInterface_Execute_Call) Return(_a0 error) *MockFilesGroupBackupInterface_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesGroupBackupInterface_Execute_Call) RunAndReturn(run func(*contexts.Context, clients.ClientInterface) error) *MockFilesGroupBackupInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Setup provides a mock function with given fields: ctx, btiOpts
func (_m *MockFilesGroupBackupInterface) Setup(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions) error {
	ret := _m.Called(ctx, btiOpts)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error); ok {
		r0 = rf(ctx, btiOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesGroupBackupInterface_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockFilesGroupBackupInterface_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions
func (_e *MockFilesGroupBackupInterface_Expecter) Setup(ctx interface{}, btiOpts interface{}) *MockFilesGroupBackupInterface_Setup_Call {
	return &MockFilesGroupBackupInterface_Setup_Call{Call: _e.mock.On("Setup", ctx, btiOpts)}
}

func (_c *MockFilesGroupBackupInterface_Setup_Call) Run(run func(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions)) *MockFilesGroupBackupInterface_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(*backuptoolinstance.CreateBackupToolInstanceOptions))
	})
	return _c
}

func (_c *MockFilesGroupBackupInterface_Setup_Call) Return(_a0 error) *MockFilesGroupBackupInterface_Setup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesGroupBackupInterface_Setup_Call) RunAndReturn(run func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error) *MockFilesGroupBackupInterface_Setup_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: ctx
func (_m *MockFilesGroupBackupInterface) Validate(ctx *contexts.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesGroupBackupInterface_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockFilesGroupBackupInterface_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockFilesGroupBackupInterface_Expecter) Validate(ctx interface{}) *MockFilesGroupBackupInterface_Validate_Call {
	return &MockFilesGroupBackupInterface_Validate_Call{Call: _e.mock.On("Validate", ctx)}
}

func (_c *MockFilesGroupBackupInterface_Validate_Call) Run(run func(ctx *contexts.Context)) *MockFilesGroupBackupInterface_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockFilesGroupBackupInterface_Validate_Call) Return(_a0 error) *MockFilesGroupBackupInterface_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesGroupBackupInterface_Validate_Call) RunAndReturn(run func(*contexts.Context) error) *MockFilesGroupBackupInterface_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFilesGroupBackupInterface creates a new instance of MockFilesGroupBackupInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilesGroupBackupInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilesGroupBackupInterface {
	mock := &MockFilesGroupBackupInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
