---
helmDefaults:
  cleanupOnFail: true
  wait: true
  waitForJobs: true
  createNamespace: false
  historyMax: 1
  timeout: 120

repositories:
  - name: bjw-s-charts
    url: https://bjw-s.github.io/helm-charts

releases:
  - name: ar-client-cas
    chart: bjw-s-charts/app-template
    version: 3.7.0
    atomic: true
    values:
      - ./client-cas.values.yaml
  - name: ar-backend
    chart: bjw-s-charts/app-template
    version: 3.7.0
    atomic: true
    needs:
      - ar-client-cas
    values:
      - ./backend.values.yaml
