---
# Source: dr-job/templates/common.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultwarden-dr-job
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dr-job
    app.kubernetes.io/version: 0.0.1-dev
    helm.sh/chart: dr-job-0.0.1-dev
secrets:
  - name: vaultwarden-dr-job-default-sa-token
---
# Source: dr-job/templates/common.yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: vaultwarden-dr-job-default-sa-token
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dr-job
    app.kubernetes.io/version: 0.0.1-dev
    helm.sh/chart: dr-job-0.0.1-dev
  annotations:
    kubernetes.io/service-account.name: vaultwarden-dr-job
---
# Source: dr-job/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-dr-job-config
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dr-job
    app.kubernetes.io/version: 0.0.1-dev
    helm.sh/chart: dr-job-0.0.1-dev
data:
  config.yaml: |
    {}
---
# Source: dr-job/templates/common.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultwarden-dr-job-backup-tool
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dr-job
    app.kubernetes.io/version: 0.0.1-dev
    helm.sh/chart: dr-job-0.0.1-dev
  
rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    - persistentvolumeclaims
    verbs:
    - create
    - get
    - list
    - watch
    - delete
  - apiGroups:
    - snapshot.storage.k8s.io
    resources:
    - volumesnapshots
    verbs:
    - create
    - get
    - list
    - watch
    - delete
  - apiGroups:
    - postgresql.cnpg.io
    resources:
    - backups
    - clusters
    verbs:
    - create
    - get
    - list
    - watch
    - delete
  - apiGroups:
    - cert-manager.io
    resources:
    - issuers
    verbs:
    - create
    - get
    - list
    - watch
    - delete
  - apiGroups:
    - cert-manager.io
    resources:
    - certificates
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - delete
  - apiGroups:
    - policy.cert-manager.io
    resources:
    - certificaterequestpolicies
    verbs:
    - create
    - get
    - list
    - watch
    - delete
---
# Source: dr-job/templates/common.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vaultwarden-dr-job-backup-tool-role
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dr-job
    app.kubernetes.io/version: 0.0.1-dev
    helm.sh/chart: dr-job-0.0.1-dev
  
roleRef:
  kind: ClusterRole
  name: vaultwarden-dr-job-backup-tool
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vaultwarden-dr-job
    namespace: default
---
# Source: dr-job/templates/common.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vaultwarden-dr-job
  labels:
    app.kubernetes.io/component: backup-tool
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dr-job
    app.kubernetes.io/version: 0.0.1-dev
    helm.sh/chart: dr-job-0.0.1-dev
spec:
  suspend: false
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  schedule: "@daily"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      parallelism: 1
      backoffLimit: 1
      template:
        metadata:
          annotations: 
            checksum/configMaps: 451501706bfd1d319a8b9c8c52e624eb3c8df721901f72515deb8f54033e24bc
            checksum/secrets: f9a2edb516d89dc9e0af00dcf3d13ae57cbe1bc631c4b35d393a497ef218d929
          labels: 
            app.kubernetes.io/component: backup-tool
            app.kubernetes.io/instance: vaultwarden
            app.kubernetes.io/name: dr-job
        spec: 
          enableServiceLinks: false
          serviceAccountName: vaultwarden-dr-job
          automountServiceAccountToken: true
          securityContext: 
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          hostIPC: false
          hostNetwork: false
          hostPID: false
          dnsPolicy: ClusterFirst
          terminationGracePeriodSeconds: 600
          restartPolicy: Never
          containers: 
            - args:
              - dr
              - vaultwarden
              - backup
              - --config-file
              - /etc/backup-tool/config.yaml
              image: ghcr.io/soliddowant/backup-tool:0.0.1-dev
              name: backup-tool
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                readOnlyRootFilesystem: true
                seccompProfile:
                  type: RuntimeDefault
              volumeMounts:
              - mountPath: /etc/backup-tool/config.yaml
                name: backup-tool
                readOnly: true
                subPath: config.yaml
          volumes: 
            - configMap:
                defaultMode: 288
                items:
                - key: config.yaml
                  path: config.yaml
                name: vaultwarden-dr-job-config
              name: backup-tool
