---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.7.0/charts/library/common/values.schema.json
rawResources:
  teleport-core-postgres-client-ca-cert:
    apiVersion: cert-manager.io/v1
    kind: Certificate
    forceRename: teleport-core-postgres-client-ca-cert
    spec:
      spec:
        commonName: Teleport Core Postgres client CA
        isCA: true
        usages:
          - cert sign
        secretTemplate:
          labels:
            cnpg.io/reload: "true"
        issuerRef:
          name: self-signed
          kind: Issuer
          group: cert-manager.io
        secretName: teleport-core-postgres-client-ca-cert
  teleport-core-postgres-auth-ca-issuer:
    apiVersion: cert-manager.io/v1
    kind: Issuer
    forceRename: teleport-core-postgres-auth-ca-issuer
    spec:
      spec:
        ca:
          secretName: teleport-core-postgres-client-ca-cert
  # This must be deployed prior to any certs, or whether cert requests
  # get approved or denied is racey
  teleport-core-postgres-auth-ca-request-policy:
    apiVersion: policy.cert-manager.io/v1alpha1
    kind: CertificateRequestPolicy
    forceRename: teleport-core-postgres-auth-ca-request-policy
    spec:
      spec:
        selector:
          issuerRef:
            group: cert-manager.io
            kind: Issuer
            name: teleport-core-postgres-auth-ca-issuer
        allowed:
          commonName:
            required: true
            value: "*"
          usages:
            - client auth
  teleport-audit-postgres-client-ca-cert:
    apiVersion: cert-manager.io/v1
    kind: Certificate
    forceRename: teleport-audit-postgres-client-ca-cert
    spec:
      spec:
        commonName: Teleport audit Postgres client CA
        isCA: true
        usages:
          - cert sign
        secretTemplate:
          labels:
            cnpg.io/reload: "true"
        issuerRef:
          name: self-signed
          kind: Issuer
          group: cert-manager.io
        secretName: teleport-audit-postgres-client-ca-cert
  teleport-audit-postgres-auth-ca-issuer:
    apiVersion: cert-manager.io/v1
    kind: Issuer
    forceRename: teleport-audit-postgres-auth-ca-issuer
    spec:
      spec:
        ca:
          secretName: teleport-audit-postgres-client-ca-cert
  # This must be deployed prior to any certs, or whether cert requests
  # get approved or denied is racey
  teleport-audit-postgres-auth-ca-request-policy:
    apiVersion: policy.cert-manager.io/v1alpha1
    kind: CertificateRequestPolicy
    forceRename: teleport-audit-postgres-auth-ca-request-policy
    spec:
      spec:
        selector:
          issuerRef:
            group: cert-manager.io
            kind: Issuer
            name: teleport-audit-postgres-auth-ca-issuer
        allowed:
          commonName:
            required: true
            value: "*"
          usages:
            - client auth
