---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.7.0/charts/library/common/values.schema.json
controllers:
  postgres-wal-bucket:
    type: job
    containers:
      create-bucket:
        image:
          repository: d3fk/s3cmd
          tag: latest
        command:
          - s3cmd
        args:
          - --access_key=$(AWS_ACCESS_KEY_ID)
          - --secret_key=$(AWS_SECRET_ACCESS_KEY)
          - --host=seaweedfs-s3:8333
          - --host-bucket=seaweedfs-s3:8333
          - --no-ssl
          - mb
          - s3://vaultwarden-wal/
        env:
          AWS_ACCESS_KEY_ID:
            valueFrom:
              secretKeyRef:
                name: seaweedfs-s3-secret
                key: admin_access_key_id
          AWS_SECRET_ACCESS_KEY:
            valueFrom:
              secretKeyRef:
                name: seaweedfs-s3-secret
                key: admin_secret_access_key
rawResources:
  postgres-serving-cert:
    apiVersion: cert-manager.io/v1
    kind: Certificate
    forceRename: postgres-serving-cert
    spec:
      spec:
        commonName: VaultWarden Postgres serving
        dnsNames:
          - vaultwarden-rw
        usages:
          - server auth
        secretTemplate:
          labels:
            cnpg.io/reload: "true"
        issuerRef:
          name: self-signed
          kind: Issuer
          group: cert-manager.io
        secretName: postgres-serving-cert
  postgres-streaming-replica-cert:
    apiVersion: cert-manager.io/v1
    kind: Certificate
    forceRename: postgres-streaming-replica-cert
    spec:
      spec:
        commonName: streaming_replica
        usages:
          - client auth
        secretTemplate:
          labels:
            cnpg.io/reload: "true"
        issuerRef:
          name: postgres-auth-ca-issuer
          kind: Issuer
          group: cert-manager.io
        secretName: postgres-streaming-replica-cert
  postgres-vaultwarden-cert:
    apiVersion: cert-manager.io/v1
    kind: Certificate
    forceRename: postgres-vaultwarden-cert
    spec:
      spec:
        commonName: vaultwarden
        usages:
          - client auth
        secretTemplate:
          labels:
            cnpg.io/reload: "true"
        issuerRef:
          name: postgres-auth-ca-issuer
          kind: Issuer
          group: cert-manager.io
        secretName: postgres-vaultwarden-cert
  postgres-vaultwarden-cluster:
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    forceRename: vaultwarden
    spec:
      spec:
        instances: 2 # One replica, one primary
        bootstrap:
          initdb:
            database: vaultwarden
            owner: vaultwarden
            postInitSQL:
              - ALTER USER vaultwarden WITH PASSWORD NULL;
        postgresql:
          pg_hba:
            - hostssl vaultwarden all all cert
        storage:
          size: 5Gi
          storageClass: openebs-zfs
        backup:
          target: prefer-standby
          volumeSnapshot:
            className: openebs-zfs
            online: true
            onlineConfiguration:
              immediateCheckpoint: false
              waitForArchive: true
            snapshotOwnerReference: backup
          barmanObjectStore:
            destinationPath: s3://vaultwarden-wal/
            endpointURL: http://seaweedfs-s3:8333
            s3Credentials:
              accessKeyId:
                name: seaweedfs-s3-secret
                key: admin_access_key_id
              secretAccessKey:
                name: seaweedfs-s3-secret
                key: admin_secret_access_key
        certificates:
          serverTLSSecret: postgres-serving-cert
          serverCASecret: postgres-serving-cert
          clientCASecret: postgres-client-ca-cert
          replicationTLSSecret: postgres-streaming-replica-cert
