---
helmDefaults:
  cleanupOnFail: true
  wait: true
  waitForJobs: true
  createNamespace: false
  historyMax: 1
  timeout: 120

repositories:
  - name: bjw-s-charts
    url: https://bjw-s-labs.github.io/helm-charts

releases:
  - name: vaultwarden-restore-client-ca
    chart: bjw-s-charts/app-template
    version: 5.0.1
    atomic: true
    values:
      - ./client-ca.values.yaml
  - name: vaultwarden-restore-backend
    chart: bjw-s-charts/app-template
    version: 5.0.1
    atomic: true
    needs:
      - vaultwarden-restore-client-ca
    values:
      - ./backend.values.yaml
