// Code generated by mockery v2.53.6. DO NOT EDIT.

package s3

import (
	context "context"

	services3 "github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// Mocks3API is an autogenerated mock type for the s3API type
type Mocks3API struct {
	mock.Mock
}

type Mocks3API_Expecter struct {
	mock *mock.Mock
}

func (_m *Mocks3API) EXPECT() *Mocks3API_Expecter {
	return &Mocks3API_Expecter{mock: &_m.Mock}
}

// DeleteObject provides a mock function with given fields: _a0, _a1, _a2
func (_m *Mocks3API) DeleteObject(_a0 context.Context, _a1 *services3.DeleteObjectInput, _a2 ...func(*services3.Options)) (*services3.DeleteObjectOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 *services3.DeleteObjectOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *services3.DeleteObjectInput, ...func(*services3.Options)) (*services3.DeleteObjectOutput, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *services3.DeleteObjectInput, ...func(*services3.Options)) *services3.DeleteObjectOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services3.DeleteObjectOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *services3.DeleteObjectInput, ...func(*services3.Options)) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mocks3API_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type Mocks3API_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *services3.DeleteObjectInput
//   - _a2 ...func(*services3.Options)
func (_e *Mocks3API_Expecter) DeleteObject(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *Mocks3API_DeleteObject_Call {
	return &Mocks3API_DeleteObject_Call{Call: _e.mock.On("DeleteObject",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *Mocks3API_DeleteObject_Call) Run(run func(_a0 context.Context, _a1 *services3.DeleteObjectInput, _a2 ...func(*services3.Options))) *Mocks3API_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*services3.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*services3.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*services3.DeleteObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3API_DeleteObject_Call) Return(_a0 *services3.DeleteObjectOutput, _a1 error) *Mocks3API_DeleteObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mocks3API_DeleteObject_Call) RunAndReturn(run func(context.Context, *services3.DeleteObjectInput, ...func(*services3.Options)) (*services3.DeleteObjectOutput, error)) *Mocks3API_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetBucketVersioning provides a mock function with given fields: _a0, _a1, _a2
func (_m *Mocks3API) GetBucketVersioning(_a0 context.Context, _a1 *services3.GetBucketVersioningInput, _a2 ...func(*services3.Options)) (*services3.GetBucketVersioningOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetBucketVersioning")
	}

	var r0 *services3.GetBucketVersioningOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *services3.GetBucketVersioningInput, ...func(*services3.Options)) (*services3.GetBucketVersioningOutput, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *services3.GetBucketVersioningInput, ...func(*services3.Options)) *services3.GetBucketVersioningOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services3.GetBucketVersioningOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *services3.GetBucketVersioningInput, ...func(*services3.Options)) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mocks3API_GetBucketVersioning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBucketVersioning'
type Mocks3API_GetBucketVersioning_Call struct {
	*mock.Call
}

// GetBucketVersioning is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *services3.GetBucketVersioningInput
//   - _a2 ...func(*services3.Options)
func (_e *Mocks3API_Expecter) GetBucketVersioning(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *Mocks3API_GetBucketVersioning_Call {
	return &Mocks3API_GetBucketVersioning_Call{Call: _e.mock.On("GetBucketVersioning",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *Mocks3API_GetBucketVersioning_Call) Run(run func(_a0 context.Context, _a1 *services3.GetBucketVersioningInput, _a2 ...func(*services3.Options))) *Mocks3API_GetBucketVersioning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*services3.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*services3.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*services3.GetBucketVersioningInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3API_GetBucketVersioning_Call) Return(_a0 *services3.GetBucketVersioningOutput, _a1 error) *Mocks3API_GetBucketVersioning_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mocks3API_GetBucketVersioning_Call) RunAndReturn(run func(context.Context, *services3.GetBucketVersioningInput, ...func(*services3.Options)) (*services3.GetBucketVersioningOutput, error)) *Mocks3API_GetBucketVersioning_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function with given fields: _a0, _a1, _a2
func (_m *Mocks3API) GetObject(_a0 context.Context, _a1 *services3.GetObjectInput, _a2 ...func(*services3.Options)) (*services3.GetObjectOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *services3.GetObjectOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *services3.GetObjectInput, ...func(*services3.Options)) (*services3.GetObjectOutput, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *services3.GetObjectInput, ...func(*services3.Options)) *services3.GetObjectOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services3.GetObjectOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *services3.GetObjectInput, ...func(*services3.Options)) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mocks3API_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type Mocks3API_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *services3.GetObjectInput
//   - _a2 ...func(*services3.Options)
func (_e *Mocks3API_Expecter) GetObject(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *Mocks3API_GetObject_Call {
	return &Mocks3API_GetObject_Call{Call: _e.mock.On("GetObject",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *Mocks3API_GetObject_Call) Run(run func(_a0 context.Context, _a1 *services3.GetObjectInput, _a2 ...func(*services3.Options))) *Mocks3API_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*services3.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*services3.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*services3.GetObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3API_GetObject_Call) Return(_a0 *services3.GetObjectOutput, _a1 error) *Mocks3API_GetObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mocks3API_GetObject_Call) RunAndReturn(run func(context.Context, *services3.GetObjectInput, ...func(*services3.Options)) (*services3.GetObjectOutput, error)) *Mocks3API_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjectVersions provides a mock function with given fields: _a0, _a1, _a2
func (_m *Mocks3API) ListObjectVersions(_a0 context.Context, _a1 *services3.ListObjectVersionsInput, _a2 ...func(*services3.Options)) (*services3.ListObjectVersionsOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListObjectVersions")
	}

	var r0 *services3.ListObjectVersionsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *services3.ListObjectVersionsInput, ...func(*services3.Options)) (*services3.ListObjectVersionsOutput, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *services3.ListObjectVersionsInput, ...func(*services3.Options)) *services3.ListObjectVersionsOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services3.ListObjectVersionsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *services3.ListObjectVersionsInput, ...func(*services3.Options)) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mocks3API_ListObjectVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjectVersions'
type Mocks3API_ListObjectVersions_Call struct {
	*mock.Call
}

// ListObjectVersions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *services3.ListObjectVersionsInput
//   - _a2 ...func(*services3.Options)
func (_e *Mocks3API_Expecter) ListObjectVersions(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *Mocks3API_ListObjectVersions_Call {
	return &Mocks3API_ListObjectVersions_Call{Call: _e.mock.On("ListObjectVersions",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *Mocks3API_ListObjectVersions_Call) Run(run func(_a0 context.Context, _a1 *services3.ListObjectVersionsInput, _a2 ...func(*services3.Options))) *Mocks3API_ListObjectVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*services3.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*services3.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*services3.ListObjectVersionsInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3API_ListObjectVersions_Call) Return(_a0 *services3.ListObjectVersionsOutput, _a1 error) *Mocks3API_ListObjectVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mocks3API_ListObjectVersions_Call) RunAndReturn(run func(context.Context, *services3.ListObjectVersionsInput, ...func(*services3.Options)) (*services3.ListObjectVersionsOutput, error)) *Mocks3API_ListObjectVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjectsV2 provides a mock function with given fields: _a0, _a1, _a2
func (_m *Mocks3API) ListObjectsV2(_a0 context.Context, _a1 *services3.ListObjectsV2Input, _a2 ...func(*services3.Options)) (*services3.ListObjectsV2Output, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListObjectsV2")
	}

	var r0 *services3.ListObjectsV2Output
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *services3.ListObjectsV2Input, ...func(*services3.Options)) (*services3.ListObjectsV2Output, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *services3.ListObjectsV2Input, ...func(*services3.Options)) *services3.ListObjectsV2Output); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services3.ListObjectsV2Output)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *services3.ListObjectsV2Input, ...func(*services3.Options)) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mocks3API_ListObjectsV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjectsV2'
type Mocks3API_ListObjectsV2_Call struct {
	*mock.Call
}

// ListObjectsV2 is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *services3.ListObjectsV2Input
//   - _a2 ...func(*services3.Options)
func (_e *Mocks3API_Expecter) ListObjectsV2(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *Mocks3API_ListObjectsV2_Call {
	return &Mocks3API_ListObjectsV2_Call{Call: _e.mock.On("ListObjectsV2",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *Mocks3API_ListObjectsV2_Call) Run(run func(_a0 context.Context, _a1 *services3.ListObjectsV2Input, _a2 ...func(*services3.Options))) *Mocks3API_ListObjectsV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*services3.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*services3.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*services3.ListObjectsV2Input), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3API_ListObjectsV2_Call) Return(_a0 *services3.ListObjectsV2Output, _a1 error) *Mocks3API_ListObjectsV2_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mocks3API_ListObjectsV2_Call) RunAndReturn(run func(context.Context, *services3.ListObjectsV2Input, ...func(*services3.Options)) (*services3.ListObjectsV2Output, error)) *Mocks3API_ListObjectsV2_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function with given fields: _a0, _a1, _a2
func (_m *Mocks3API) PutObject(_a0 context.Context, _a1 *services3.PutObjectInput, _a2 ...func(*services3.Options)) (*services3.PutObjectOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *services3.PutObjectOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *services3.PutObjectInput, ...func(*services3.Options)) (*services3.PutObjectOutput, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *services3.PutObjectInput, ...func(*services3.Options)) *services3.PutObjectOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services3.PutObjectOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *services3.PutObjectInput, ...func(*services3.Options)) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mocks3API_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type Mocks3API_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *services3.PutObjectInput
//   - _a2 ...func(*services3.Options)
func (_e *Mocks3API_Expecter) PutObject(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *Mocks3API_PutObject_Call {
	return &Mocks3API_PutObject_Call{Call: _e.mock.On("PutObject",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *Mocks3API_PutObject_Call) Run(run func(_a0 context.Context, _a1 *services3.PutObjectInput, _a2 ...func(*services3.Options))) *Mocks3API_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*services3.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*services3.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*services3.PutObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3API_PutObject_Call) Return(_a0 *services3.PutObjectOutput, _a1 error) *Mocks3API_PutObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mocks3API_PutObject_Call) RunAndReturn(run func(context.Context, *services3.PutObjectInput, ...func(*services3.Options)) (*services3.PutObjectOutput, error)) *Mocks3API_PutObject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocks3API creates a new instance of Mocks3API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocks3API(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mocks3API {
	mock := &Mocks3API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
