// Code generated by mockery v2.53.6. DO NOT EDIT.

package grouprestore

import (
	clients "github.com/solidDoWant/backup-tool/pkg/grpc/clients"
	backuptoolinstance "github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/backuptoolinstance"

	contexts "github.com/solidDoWant/backup-tool/pkg/contexts"

	kubecluster "github.com/solidDoWant/backup-tool/pkg/kubecluster"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MockFilesGroupRestoreInterface is an autogenerated mock type for the FilesGroupRestoreInterface type
type MockFilesGroupRestoreInterface struct {
	mock.Mock
}

type MockFilesGroupRestoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilesGroupRestoreInterface) EXPECT() *MockFilesGroupRestoreInterface_Expecter {
	return &MockFilesGroupRestoreInterface_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function with given fields: kubeClusterClient, namespace, selector, drVolName, groupName, opts
func (_m *MockFilesGroupRestoreInterface) Configure(kubeClusterClient kubecluster.ClientInterface, namespace string, selector v1.LabelSelector, drVolName string, groupName string, opts FilesGroupRestoreOptions) error {
	ret := _m.Called(kubeClusterClient, namespace, selector, drVolName, groupName, opts)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(kubecluster.ClientInterface, string, v1.LabelSelector, string, string, FilesGroupRestoreOptions) error); ok {
		r0 = rf(kubeClusterClient, namespace, selector, drVolName, groupName, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesGroupRestoreInterface_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockFilesGroupRestoreInterface_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - kubeClusterClient kubecluster.ClientInterface
//   - namespace string
//   - selector v1.LabelSelector
//   - drVolName string
//   - groupName string
//   - opts FilesGroupRestoreOptions
func (_e *MockFilesGroupRestoreInterface_Expecter) Configure(kubeClusterClient interface{}, namespace interface{}, selector interface{}, drVolName interface{}, groupName interface{}, opts interface{}) *MockFilesGroupRestoreInterface_Configure_Call {
	return &MockFilesGroupRestoreInterface_Configure_Call{Call: _e.mock.On("Configure", kubeClusterClient, namespace, selector, drVolName, groupName, opts)}
}

func (_c *MockFilesGroupRestoreInterface_Configure_Call) Run(run func(kubeClusterClient kubecluster.ClientInterface, namespace string, selector v1.LabelSelector, drVolName string, groupName string, opts FilesGroupRestoreOptions)) *MockFilesGroupRestoreInterface_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(kubecluster.ClientInterface), args[1].(string), args[2].(v1.LabelSelector), args[3].(string), args[4].(string), args[5].(FilesGroupRestoreOptions))
	})
	return _c
}

func (_c *MockFilesGroupRestoreInterface_Configure_Call) Return(_a0 error) *MockFilesGroupRestoreInterface_Configure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesGroupRestoreInterface_Configure_Call) RunAndReturn(run func(kubecluster.ClientInterface, string, v1.LabelSelector, string, string, FilesGroupRestoreOptions) error) *MockFilesGroupRestoreInterface_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: ctx, backupToolClient
func (_m *MockFilesGroupRestoreInterface) Execute(ctx *contexts.Context, backupToolClient clients.ClientInterface) error {
	ret := _m.Called(ctx, backupToolClient)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, clients.ClientInterface) error); ok {
		r0 = rf(ctx, backupToolClient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesGroupRestoreInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFilesGroupRestoreInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - backupToolClient clients.ClientInterface
func (_e *MockFilesGroupRestoreInterface_Expecter) Execute(ctx interface{}, backupToolClient interface{}) *MockFilesGroupRestoreInterface_Execute_Call {
	return &MockFilesGroupRestoreInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, backupToolClient)}
}

func (_c *MockFilesGroupRestoreInterface_Execute_Call) Run(run func(ctx *contexts.Context, backupToolClient clients.ClientInterface)) *MockFilesGroupRestoreInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(clients.ClientInterface))
	})
	return _c
}

func (_c *MockFilesGroupRestoreInterface_Execute_Call) Return(_a0 error) *MockFilesGroupRestoreInterface_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesGroupRestoreInterface_Execute_Call) RunAndReturn(run func(*contexts.Context, clients.ClientInterface) error) *MockFilesGroupRestoreInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Setup provides a mock function with given fields: ctx, btiOpts
func (_m *MockFilesGroupRestoreInterface) Setup(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions) error {
	ret := _m.Called(ctx, btiOpts)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error); ok {
		r0 = rf(ctx, btiOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesGroupRestoreInterface_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockFilesGroupRestoreInterface_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions
func (_e *MockFilesGroupRestoreInterface_Expecter) Setup(ctx interface{}, btiOpts interface{}) *MockFilesGroupRestoreInterface_Setup_Call {
	return &MockFilesGroupRestoreInterface_Setup_Call{Call: _e.mock.On("Setup", ctx, btiOpts)}
}

func (_c *MockFilesGroupRestoreInterface_Setup_Call) Run(run func(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions)) *MockFilesGroupRestoreInterface_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(*backuptoolinstance.CreateBackupToolInstanceOptions))
	})
	return _c
}

func (_c *MockFilesGroupRestoreInterface_Setup_Call) Return(_a0 error) *MockFilesGroupRestoreInterface_Setup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesGroupRestoreInterface_Setup_Call) RunAndReturn(run func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error) *MockFilesGroupRestoreInterface_Setup_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: ctx
func (_m *MockFilesGroupRestoreInterface) Validate(ctx *contexts.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesGroupRestoreInterface_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockFilesGroupRestoreInterface_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockFilesGroupRestoreInterface_Expecter) Validate(ctx interface{}) *MockFilesGroupRestoreInterface_Validate_Call {
	return &MockFilesGroupRestoreInterface_Validate_Call{Call: _e.mock.On("Validate", ctx)}
}

func (_c *MockFilesGroupRestoreInterface_Validate_Call) Run(run func(ctx *contexts.Context)) *MockFilesGroupRestoreInterface_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockFilesGroupRestoreInterface_Validate_Call) Return(_a0 error) *MockFilesGroupRestoreInterface_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesGroupRestoreInterface_Validate_Call) RunAndReturn(run func(*contexts.Context) error) *MockFilesGroupRestoreInterface_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFilesGroupRestoreInterface creates a new instance of MockFilesGroupRestoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilesGroupRestoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilesGroupRestoreInterface {
	mock := &MockFilesGroupRestoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
