// Code generated by mockery v2.51.0. DO NOT EDIT.

package features

import (
	kubecluster "github.com/solidDoWant/backup-tool/pkg/kubecluster"
	cobra "github.com/spf13/cobra"
	mock "github.com/stretchr/testify/mock"

	rest "k8s.io/client-go/rest"
)

// MockKubeClusterCommandInterface is an autogenerated mock type for the KubeClusterCommandInterface type
type MockKubeClusterCommandInterface struct {
	mock.Mock
}

type MockKubeClusterCommandInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKubeClusterCommandInterface) EXPECT() *MockKubeClusterCommandInterface_Expecter {
	return &MockKubeClusterCommandInterface_Expecter{mock: &_m.Mock}
}

// ConfigureFlags provides a mock function with given fields: cmd
func (_m *MockKubeClusterCommandInterface) ConfigureFlags(cmd *cobra.Command) {
	_m.Called(cmd)
}

// MockKubeClusterCommandInterface_ConfigureFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigureFlags'
type MockKubeClusterCommandInterface_ConfigureFlags_Call struct {
	*mock.Call
}

// ConfigureFlags is a helper method to define mock.On call
//   - cmd *cobra.Command
func (_e *MockKubeClusterCommandInterface_Expecter) ConfigureFlags(cmd interface{}) *MockKubeClusterCommandInterface_ConfigureFlags_Call {
	return &MockKubeClusterCommandInterface_ConfigureFlags_Call{Call: _e.mock.On("ConfigureFlags", cmd)}
}

func (_c *MockKubeClusterCommandInterface_ConfigureFlags_Call) Run(run func(cmd *cobra.Command)) *MockKubeClusterCommandInterface_ConfigureFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*cobra.Command))
	})
	return _c
}

func (_c *MockKubeClusterCommandInterface_ConfigureFlags_Call) Return() *MockKubeClusterCommandInterface_ConfigureFlags_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockKubeClusterCommandInterface_ConfigureFlags_Call) RunAndReturn(run func(*cobra.Command)) *MockKubeClusterCommandInterface_ConfigureFlags_Call {
	_c.Run(run)
	return _c
}

// GetClusterConfig provides a mock function with no fields
func (_m *MockKubeClusterCommandInterface) GetClusterConfig() (*rest.Config, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClusterConfig")
	}

	var r0 *rest.Config
	var r1 error
	if rf, ok := ret.Get(0).(func() (*rest.Config, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *rest.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Config)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKubeClusterCommandInterface_GetClusterConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterConfig'
type MockKubeClusterCommandInterface_GetClusterConfig_Call struct {
	*mock.Call
}

// GetClusterConfig is a helper method to define mock.On call
func (_e *MockKubeClusterCommandInterface_Expecter) GetClusterConfig() *MockKubeClusterCommandInterface_GetClusterConfig_Call {
	return &MockKubeClusterCommandInterface_GetClusterConfig_Call{Call: _e.mock.On("GetClusterConfig")}
}

func (_c *MockKubeClusterCommandInterface_GetClusterConfig_Call) Run(run func()) *MockKubeClusterCommandInterface_GetClusterConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKubeClusterCommandInterface_GetClusterConfig_Call) Return(_a0 *rest.Config, _a1 error) *MockKubeClusterCommandInterface_GetClusterConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKubeClusterCommandInterface_GetClusterConfig_Call) RunAndReturn(run func() (*rest.Config, error)) *MockKubeClusterCommandInterface_GetClusterConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewKubeClusterClient provides a mock function with no fields
func (_m *MockKubeClusterCommandInterface) NewKubeClusterClient() (kubecluster.ClientInterface, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewKubeClusterClient")
	}

	var r0 kubecluster.ClientInterface
	var r1 error
	if rf, ok := ret.Get(0).(func() (kubecluster.ClientInterface, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() kubecluster.ClientInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kubecluster.ClientInterface)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKubeClusterCommandInterface_NewKubeClusterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewKubeClusterClient'
type MockKubeClusterCommandInterface_NewKubeClusterClient_Call struct {
	*mock.Call
}

// NewKubeClusterClient is a helper method to define mock.On call
func (_e *MockKubeClusterCommandInterface_Expecter) NewKubeClusterClient() *MockKubeClusterCommandInterface_NewKubeClusterClient_Call {
	return &MockKubeClusterCommandInterface_NewKubeClusterClient_Call{Call: _e.mock.On("NewKubeClusterClient")}
}

func (_c *MockKubeClusterCommandInterface_NewKubeClusterClient_Call) Run(run func()) *MockKubeClusterCommandInterface_NewKubeClusterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKubeClusterCommandInterface_NewKubeClusterClient_Call) Return(_a0 kubecluster.ClientInterface, _a1 error) *MockKubeClusterCommandInterface_NewKubeClusterClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKubeClusterCommandInterface_NewKubeClusterClient_Call) RunAndReturn(run func() (kubecluster.ClientInterface, error)) *MockKubeClusterCommandInterface_NewKubeClusterClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKubeClusterCommandInterface creates a new instance of MockKubeClusterCommandInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKubeClusterCommandInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKubeClusterCommandInterface {
	mock := &MockKubeClusterCommandInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
