// Code generated by mockery v2.51.0. DO NOT EDIT.

package disasterrecovery

import mock "github.com/stretchr/testify/mock"

// MockDRBackupCommand is an autogenerated mock type for the DRBackupCommand type
type MockDRBackupCommand struct {
	mock.Mock
}

type MockDRBackupCommand_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDRBackupCommand) EXPECT() *MockDRBackupCommand_Expecter {
	return &MockDRBackupCommand_Expecter{mock: &_m.Mock}
}

// GetBackupCommand provides a mock function with no fields
func (_m *MockDRBackupCommand) GetBackupCommand() DREventCommand {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBackupCommand")
	}

	var r0 DREventCommand
	if rf, ok := ret.Get(0).(func() DREventCommand); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(DREventCommand)
		}
	}

	return r0
}

// MockDRBackupCommand_GetBackupCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackupCommand'
type MockDRBackupCommand_GetBackupCommand_Call struct {
	*mock.Call
}

// GetBackupCommand is a helper method to define mock.On call
func (_e *MockDRBackupCommand_Expecter) GetBackupCommand() *MockDRBackupCommand_GetBackupCommand_Call {
	return &MockDRBackupCommand_GetBackupCommand_Call{Call: _e.mock.On("GetBackupCommand")}
}

func (_c *MockDRBackupCommand_GetBackupCommand_Call) Run(run func()) *MockDRBackupCommand_GetBackupCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDRBackupCommand_GetBackupCommand_Call) Return(_a0 DREventCommand) *MockDRBackupCommand_GetBackupCommand_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDRBackupCommand_GetBackupCommand_Call) RunAndReturn(run func() DREventCommand) *MockDRBackupCommand_GetBackupCommand_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockDRBackupCommand) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDRBackupCommand_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDRBackupCommand_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDRBackupCommand_Expecter) Name() *MockDRBackupCommand_Name_Call {
	return &MockDRBackupCommand_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDRBackupCommand_Name_Call) Run(run func()) *MockDRBackupCommand_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDRBackupCommand_Name_Call) Return(_a0 string) *MockDRBackupCommand_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDRBackupCommand_Name_Call) RunAndReturn(run func() string) *MockDRBackupCommand_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDRBackupCommand creates a new instance of MockDRBackupCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDRBackupCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDRBackupCommand {
	mock := &MockDRBackupCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
