// Code generated by mockery v2.51.0. DO NOT EDIT.

package disasterrecovery

import mock "github.com/stretchr/testify/mock"

// MockDRRestoreCommand is an autogenerated mock type for the DRRestoreCommand type
type MockDRRestoreCommand struct {
	mock.Mock
}

type MockDRRestoreCommand_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDRRestoreCommand) EXPECT() *MockDRRestoreCommand_Expecter {
	return &MockDRRestoreCommand_Expecter{mock: &_m.Mock}
}

// GetRestoreCommand provides a mock function with no fields
func (_m *MockDRRestoreCommand) GetRestoreCommand() DREventCommand {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRestoreCommand")
	}

	var r0 DREventCommand
	if rf, ok := ret.Get(0).(func() DREventCommand); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(DREventCommand)
		}
	}

	return r0
}

// MockDRRestoreCommand_GetRestoreCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRestoreCommand'
type MockDRRestoreCommand_GetRestoreCommand_Call struct {
	*mock.Call
}

// GetRestoreCommand is a helper method to define mock.On call
func (_e *MockDRRestoreCommand_Expecter) GetRestoreCommand() *MockDRRestoreCommand_GetRestoreCommand_Call {
	return &MockDRRestoreCommand_GetRestoreCommand_Call{Call: _e.mock.On("GetRestoreCommand")}
}

func (_c *MockDRRestoreCommand_GetRestoreCommand_Call) Run(run func()) *MockDRRestoreCommand_GetRestoreCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDRRestoreCommand_GetRestoreCommand_Call) Return(_a0 DREventCommand) *MockDRRestoreCommand_GetRestoreCommand_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDRRestoreCommand_GetRestoreCommand_Call) RunAndReturn(run func() DREventCommand) *MockDRRestoreCommand_GetRestoreCommand_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockDRRestoreCommand) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDRRestoreCommand_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDRRestoreCommand_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDRRestoreCommand_Expecter) Name() *MockDRRestoreCommand_Name_Call {
	return &MockDRRestoreCommand_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDRRestoreCommand_Name_Call) Run(run func()) *MockDRRestoreCommand_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDRRestoreCommand_Name_Call) Return(_a0 string) *MockDRRestoreCommand_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDRRestoreCommand_Name_Call) RunAndReturn(run func() string) *MockDRRestoreCommand_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDRRestoreCommand creates a new instance of MockDRRestoreCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDRRestoreCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDRRestoreCommand {
	mock := &MockDRRestoreCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
