// Code generated by mockery v2.51.0. DO NOT EDIT.

package certmanager

import (
	contexts "github.com/solidDoWant/backup-tool/pkg/contexts"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1"
)

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

type MockClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInterface) EXPECT() *MockClientInterface_Expecter {
	return &MockClientInterface_Expecter{mock: &_m.Mock}
}

// CreateCertificate provides a mock function with given fields: ctx, namespace, name, issuerName, opts
func (_m *MockClientInterface) CreateCertificate(ctx *contexts.Context, namespace string, name string, issuerName string, opts CreateCertificateOptions) (*v1.Certificate, error) {
	ret := _m.Called(ctx, namespace, name, issuerName, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateCertificate")
	}

	var r0 *v1.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, string, CreateCertificateOptions) (*v1.Certificate, error)); ok {
		return rf(ctx, namespace, name, issuerName, opts)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, string, CreateCertificateOptions) *v1.Certificate); ok {
		r0 = rf(ctx, namespace, name, issuerName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context, string, string, string, CreateCertificateOptions) error); ok {
		r1 = rf(ctx, namespace, name, issuerName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_CreateCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCertificate'
type MockClientInterface_CreateCertificate_Call struct {
	*mock.Call
}

// CreateCertificate is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - name string
//   - issuerName string
//   - opts CreateCertificateOptions
func (_e *MockClientInterface_Expecter) CreateCertificate(ctx interface{}, namespace interface{}, name interface{}, issuerName interface{}, opts interface{}) *MockClientInterface_CreateCertificate_Call {
	return &MockClientInterface_CreateCertificate_Call{Call: _e.mock.On("CreateCertificate", ctx, namespace, name, issuerName, opts)}
}

func (_c *MockClientInterface_CreateCertificate_Call) Run(run func(ctx *contexts.Context, namespace string, name string, issuerName string, opts CreateCertificateOptions)) *MockClientInterface_CreateCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(CreateCertificateOptions))
	})
	return _c
}

func (_c *MockClientInterface_CreateCertificate_Call) Return(_a0 *v1.Certificate, _a1 error) *MockClientInterface_CreateCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_CreateCertificate_Call) RunAndReturn(run func(*contexts.Context, string, string, string, CreateCertificateOptions) (*v1.Certificate, error)) *MockClientInterface_CreateCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIssuer provides a mock function with given fields: ctx, namespace, name, caCertSecretName, opts
func (_m *MockClientInterface) CreateIssuer(ctx *contexts.Context, namespace string, name string, caCertSecretName string, opts CreateIssuerOptions) (*v1.Issuer, error) {
	ret := _m.Called(ctx, namespace, name, caCertSecretName, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateIssuer")
	}

	var r0 *v1.Issuer
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, string, CreateIssuerOptions) (*v1.Issuer, error)); ok {
		return rf(ctx, namespace, name, caCertSecretName, opts)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, string, CreateIssuerOptions) *v1.Issuer); ok {
		r0 = rf(ctx, namespace, name, caCertSecretName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Issuer)
		}
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context, string, string, string, CreateIssuerOptions) error); ok {
		r1 = rf(ctx, namespace, name, caCertSecretName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_CreateIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIssuer'
type MockClientInterface_CreateIssuer_Call struct {
	*mock.Call
}

// CreateIssuer is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - name string
//   - caCertSecretName string
//   - opts CreateIssuerOptions
func (_e *MockClientInterface_Expecter) CreateIssuer(ctx interface{}, namespace interface{}, name interface{}, caCertSecretName interface{}, opts interface{}) *MockClientInterface_CreateIssuer_Call {
	return &MockClientInterface_CreateIssuer_Call{Call: _e.mock.On("CreateIssuer", ctx, namespace, name, caCertSecretName, opts)}
}

func (_c *MockClientInterface_CreateIssuer_Call) Run(run func(ctx *contexts.Context, namespace string, name string, caCertSecretName string, opts CreateIssuerOptions)) *MockClientInterface_CreateIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(CreateIssuerOptions))
	})
	return _c
}

func (_c *MockClientInterface_CreateIssuer_Call) Return(_a0 *v1.Issuer, _a1 error) *MockClientInterface_CreateIssuer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_CreateIssuer_Call) RunAndReturn(run func(*contexts.Context, string, string, string, CreateIssuerOptions) (*v1.Issuer, error)) *MockClientInterface_CreateIssuer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCertificate provides a mock function with given fields: ctx, namespace, name
func (_m *MockClientInterface) DeleteCertificate(ctx *contexts.Context, namespace string, name string) error {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string) error); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientInterface_DeleteCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCertificate'
type MockClientInterface_DeleteCertificate_Call struct {
	*mock.Call
}

// DeleteCertificate is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - name string
func (_e *MockClientInterface_Expecter) DeleteCertificate(ctx interface{}, namespace interface{}, name interface{}) *MockClientInterface_DeleteCertificate_Call {
	return &MockClientInterface_DeleteCertificate_Call{Call: _e.mock.On("DeleteCertificate", ctx, namespace, name)}
}

func (_c *MockClientInterface_DeleteCertificate_Call) Run(run func(ctx *contexts.Context, namespace string, name string)) *MockClientInterface_DeleteCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientInterface_DeleteCertificate_Call) Return(_a0 error) *MockClientInterface_DeleteCertificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientInterface_DeleteCertificate_Call) RunAndReturn(run func(*contexts.Context, string, string) error) *MockClientInterface_DeleteCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIssuer provides a mock function with given fields: ctx, namespace, name
func (_m *MockClientInterface) DeleteIssuer(ctx *contexts.Context, namespace string, name string) error {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIssuer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string) error); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientInterface_DeleteIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIssuer'
type MockClientInterface_DeleteIssuer_Call struct {
	*mock.Call
}

// DeleteIssuer is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - name string
func (_e *MockClientInterface_Expecter) DeleteIssuer(ctx interface{}, namespace interface{}, name interface{}) *MockClientInterface_DeleteIssuer_Call {
	return &MockClientInterface_DeleteIssuer_Call{Call: _e.mock.On("DeleteIssuer", ctx, namespace, name)}
}

func (_c *MockClientInterface_DeleteIssuer_Call) Run(run func(ctx *contexts.Context, namespace string, name string)) *MockClientInterface_DeleteIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientInterface_DeleteIssuer_Call) Return(_a0 error) *MockClientInterface_DeleteIssuer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientInterface_DeleteIssuer_Call) RunAndReturn(run func(*contexts.Context, string, string) error) *MockClientInterface_DeleteIssuer_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificate provides a mock function with given fields: ctx, namespace, name
func (_m *MockClientInterface) GetCertificate(ctx *contexts.Context, namespace string, name string) (*v1.Certificate, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificate")
	}

	var r0 *v1.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string) (*v1.Certificate, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string) *v1.Certificate); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_GetCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificate'
type MockClientInterface_GetCertificate_Call struct {
	*mock.Call
}

// GetCertificate is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - name string
func (_e *MockClientInterface_Expecter) GetCertificate(ctx interface{}, namespace interface{}, name interface{}) *MockClientInterface_GetCertificate_Call {
	return &MockClientInterface_GetCertificate_Call{Call: _e.mock.On("GetCertificate", ctx, namespace, name)}
}

func (_c *MockClientInterface_GetCertificate_Call) Run(run func(ctx *contexts.Context, namespace string, name string)) *MockClientInterface_GetCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientInterface_GetCertificate_Call) Return(_a0 *v1.Certificate, _a1 error) *MockClientInterface_GetCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_GetCertificate_Call) RunAndReturn(run func(*contexts.Context, string, string) (*v1.Certificate, error)) *MockClientInterface_GetCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssuer provides a mock function with given fields: ctx, namespace, name
func (_m *MockClientInterface) GetIssuer(ctx *contexts.Context, namespace string, name string) (*v1.Issuer, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetIssuer")
	}

	var r0 *v1.Issuer
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string) (*v1.Issuer, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string) *v1.Issuer); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Issuer)
		}
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_GetIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssuer'
type MockClientInterface_GetIssuer_Call struct {
	*mock.Call
}

// GetIssuer is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - name string
func (_e *MockClientInterface_Expecter) GetIssuer(ctx interface{}, namespace interface{}, name interface{}) *MockClientInterface_GetIssuer_Call {
	return &MockClientInterface_GetIssuer_Call{Call: _e.mock.On("GetIssuer", ctx, namespace, name)}
}

func (_c *MockClientInterface_GetIssuer_Call) Run(run func(ctx *contexts.Context, namespace string, name string)) *MockClientInterface_GetIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientInterface_GetIssuer_Call) Return(_a0 *v1.Issuer, _a1 error) *MockClientInterface_GetIssuer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_GetIssuer_Call) RunAndReturn(run func(*contexts.Context, string, string) (*v1.Issuer, error)) *MockClientInterface_GetIssuer_Call {
	_c.Call.Return(run)
	return _c
}

// ReissueCertificate provides a mock function with given fields: ctx, namespace, name
func (_m *MockClientInterface) ReissueCertificate(ctx *contexts.Context, namespace string, name string) (*v1.Certificate, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for ReissueCertificate")
	}

	var r0 *v1.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string) (*v1.Certificate, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string) *v1.Certificate); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_ReissueCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReissueCertificate'
type MockClientInterface_ReissueCertificate_Call struct {
	*mock.Call
}

// ReissueCertificate is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - name string
func (_e *MockClientInterface_Expecter) ReissueCertificate(ctx interface{}, namespace interface{}, name interface{}) *MockClientInterface_ReissueCertificate_Call {
	return &MockClientInterface_ReissueCertificate_Call{Call: _e.mock.On("ReissueCertificate", ctx, namespace, name)}
}

func (_c *MockClientInterface_ReissueCertificate_Call) Run(run func(ctx *contexts.Context, namespace string, name string)) *MockClientInterface_ReissueCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientInterface_ReissueCertificate_Call) Return(_a0 *v1.Certificate, _a1 error) *MockClientInterface_ReissueCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_ReissueCertificate_Call) RunAndReturn(run func(*contexts.Context, string, string) (*v1.Certificate, error)) *MockClientInterface_ReissueCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForReadyCertificate provides a mock function with given fields: ctx, namespace, name, opts
func (_m *MockClientInterface) WaitForReadyCertificate(ctx *contexts.Context, namespace string, name string, opts WaitForReadyCertificateOpts) (*v1.Certificate, error) {
	ret := _m.Called(ctx, namespace, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for WaitForReadyCertificate")
	}

	var r0 *v1.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, WaitForReadyCertificateOpts) (*v1.Certificate, error)); ok {
		return rf(ctx, namespace, name, opts)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, WaitForReadyCertificateOpts) *v1.Certificate); ok {
		r0 = rf(ctx, namespace, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context, string, string, WaitForReadyCertificateOpts) error); ok {
		r1 = rf(ctx, namespace, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_WaitForReadyCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForReadyCertificate'
type MockClientInterface_WaitForReadyCertificate_Call struct {
	*mock.Call
}

// WaitForReadyCertificate is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - name string
//   - opts WaitForReadyCertificateOpts
func (_e *MockClientInterface_Expecter) WaitForReadyCertificate(ctx interface{}, namespace interface{}, name interface{}, opts interface{}) *MockClientInterface_WaitForReadyCertificate_Call {
	return &MockClientInterface_WaitForReadyCertificate_Call{Call: _e.mock.On("WaitForReadyCertificate", ctx, namespace, name, opts)}
}

func (_c *MockClientInterface_WaitForReadyCertificate_Call) Run(run func(ctx *contexts.Context, namespace string, name string, opts WaitForReadyCertificateOpts)) *MockClientInterface_WaitForReadyCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string), args[3].(WaitForReadyCertificateOpts))
	})
	return _c
}

func (_c *MockClientInterface_WaitForReadyCertificate_Call) Return(_a0 *v1.Certificate, _a1 error) *MockClientInterface_WaitForReadyCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_WaitForReadyCertificate_Call) RunAndReturn(run func(*contexts.Context, string, string, WaitForReadyCertificateOpts) (*v1.Certificate, error)) *MockClientInterface_WaitForReadyCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForReadyIssuer provides a mock function with given fields: ctx, namespace, name, opts
func (_m *MockClientInterface) WaitForReadyIssuer(ctx *contexts.Context, namespace string, name string, opts WaitForReadyIssuerOpts) (*v1.Issuer, error) {
	ret := _m.Called(ctx, namespace, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for WaitForReadyIssuer")
	}

	var r0 *v1.Issuer
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, WaitForReadyIssuerOpts) (*v1.Issuer, error)); ok {
		return rf(ctx, namespace, name, opts)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, WaitForReadyIssuerOpts) *v1.Issuer); ok {
		r0 = rf(ctx, namespace, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Issuer)
		}
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context, string, string, WaitForReadyIssuerOpts) error); ok {
		r1 = rf(ctx, namespace, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_WaitForReadyIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForReadyIssuer'
type MockClientInterface_WaitForReadyIssuer_Call struct {
	*mock.Call
}

// WaitForReadyIssuer is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - name string
//   - opts WaitForReadyIssuerOpts
func (_e *MockClientInterface_Expecter) WaitForReadyIssuer(ctx interface{}, namespace interface{}, name interface{}, opts interface{}) *MockClientInterface_WaitForReadyIssuer_Call {
	return &MockClientInterface_WaitForReadyIssuer_Call{Call: _e.mock.On("WaitForReadyIssuer", ctx, namespace, name, opts)}
}

func (_c *MockClientInterface_WaitForReadyIssuer_Call) Run(run func(ctx *contexts.Context, namespace string, name string, opts WaitForReadyIssuerOpts)) *MockClientInterface_WaitForReadyIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string), args[3].(WaitForReadyIssuerOpts))
	})
	return _c
}

func (_c *MockClientInterface_WaitForReadyIssuer_Call) Return(_a0 *v1.Issuer, _a1 error) *MockClientInterface_WaitForReadyIssuer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_WaitForReadyIssuer_Call) RunAndReturn(run func(*contexts.Context, string, string, WaitForReadyIssuerOpts) (*v1.Issuer, error)) *MockClientInterface_WaitForReadyIssuer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
