// Code generated by mockery v2.53.6. DO NOT EDIT.

package backup

import (
	clients "github.com/solidDoWant/backup-tool/pkg/grpc/clients"
	backuptoolinstance "github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/backuptoolinstance"

	contexts "github.com/solidDoWant/backup-tool/pkg/contexts"

	kubecluster "github.com/solidDoWant/backup-tool/pkg/kubecluster"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockFilesBackupInterface is an autogenerated mock type for the FilesBackupInterface type
type MockFilesBackupInterface struct {
	mock.Mock
}

type MockFilesBackupInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilesBackupInterface) EXPECT() *MockFilesBackupInterface_Expecter {
	return &MockFilesBackupInterface_Expecter{mock: &_m.Mock}
}

// BeforeConsistencyPoint provides a mock function with given fields: ctx
func (_m *MockFilesBackupInterface) BeforeConsistencyPoint(ctx *contexts.Context) (time.Time, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeforeConsistencyPoint")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) (time.Time, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context) time.Time); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFilesBackupInterface_BeforeConsistencyPoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeforeConsistencyPoint'
type MockFilesBackupInterface_BeforeConsistencyPoint_Call struct {
	*mock.Call
}

// BeforeConsistencyPoint is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockFilesBackupInterface_Expecter) BeforeConsistencyPoint(ctx interface{}) *MockFilesBackupInterface_BeforeConsistencyPoint_Call {
	return &MockFilesBackupInterface_BeforeConsistencyPoint_Call{Call: _e.mock.On("BeforeConsistencyPoint", ctx)}
}

func (_c *MockFilesBackupInterface_BeforeConsistencyPoint_Call) Run(run func(ctx *contexts.Context)) *MockFilesBackupInterface_BeforeConsistencyPoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockFilesBackupInterface_BeforeConsistencyPoint_Call) Return(_a0 time.Time, _a1 error) *MockFilesBackupInterface_BeforeConsistencyPoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFilesBackupInterface_BeforeConsistencyPoint_Call) RunAndReturn(run func(*contexts.Context) (time.Time, error)) *MockFilesBackupInterface_BeforeConsistencyPoint_Call {
	_c.Call.Return(run)
	return _c
}

// Cleanup provides a mock function with given fields: ctx
func (_m *MockFilesBackupInterface) Cleanup(ctx *contexts.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesBackupInterface_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockFilesBackupInterface_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockFilesBackupInterface_Expecter) Cleanup(ctx interface{}) *MockFilesBackupInterface_Cleanup_Call {
	return &MockFilesBackupInterface_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx)}
}

func (_c *MockFilesBackupInterface_Cleanup_Call) Run(run func(ctx *contexts.Context)) *MockFilesBackupInterface_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockFilesBackupInterface_Cleanup_Call) Return(_a0 error) *MockFilesBackupInterface_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesBackupInterface_Cleanup_Call) RunAndReturn(run func(*contexts.Context) error) *MockFilesBackupInterface_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Configure provides a mock function with given fields: kubeClusterClient, namespace, sourcePVCName, drVolName, backupDirRelPath, opts
func (_m *MockFilesBackupInterface) Configure(kubeClusterClient kubecluster.ClientInterface, namespace string, sourcePVCName string, drVolName string, backupDirRelPath string, opts FilesBackupOptions) error {
	ret := _m.Called(kubeClusterClient, namespace, sourcePVCName, drVolName, backupDirRelPath, opts)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(kubecluster.ClientInterface, string, string, string, string, FilesBackupOptions) error); ok {
		r0 = rf(kubeClusterClient, namespace, sourcePVCName, drVolName, backupDirRelPath, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesBackupInterface_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockFilesBackupInterface_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - kubeClusterClient kubecluster.ClientInterface
//   - namespace string
//   - sourcePVCName string
//   - drVolName string
//   - backupDirRelPath string
//   - opts FilesBackupOptions
func (_e *MockFilesBackupInterface_Expecter) Configure(kubeClusterClient interface{}, namespace interface{}, sourcePVCName interface{}, drVolName interface{}, backupDirRelPath interface{}, opts interface{}) *MockFilesBackupInterface_Configure_Call {
	return &MockFilesBackupInterface_Configure_Call{Call: _e.mock.On("Configure", kubeClusterClient, namespace, sourcePVCName, drVolName, backupDirRelPath, opts)}
}

func (_c *MockFilesBackupInterface_Configure_Call) Run(run func(kubeClusterClient kubecluster.ClientInterface, namespace string, sourcePVCName string, drVolName string, backupDirRelPath string, opts FilesBackupOptions)) *MockFilesBackupInterface_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(kubecluster.ClientInterface), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(FilesBackupOptions))
	})
	return _c
}

func (_c *MockFilesBackupInterface_Configure_Call) Return(_a0 error) *MockFilesBackupInterface_Configure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesBackupInterface_Configure_Call) RunAndReturn(run func(kubecluster.ClientInterface, string, string, string, string, FilesBackupOptions) error) *MockFilesBackupInterface_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: ctx, backupToolClient
func (_m *MockFilesBackupInterface) Execute(ctx *contexts.Context, backupToolClient clients.ClientInterface) error {
	ret := _m.Called(ctx, backupToolClient)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, clients.ClientInterface) error); ok {
		r0 = rf(ctx, backupToolClient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesBackupInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFilesBackupInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - backupToolClient clients.ClientInterface
func (_e *MockFilesBackupInterface_Expecter) Execute(ctx interface{}, backupToolClient interface{}) *MockFilesBackupInterface_Execute_Call {
	return &MockFilesBackupInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, backupToolClient)}
}

func (_c *MockFilesBackupInterface_Execute_Call) Run(run func(ctx *contexts.Context, backupToolClient clients.ClientInterface)) *MockFilesBackupInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(clients.ClientInterface))
	})
	return _c
}

func (_c *MockFilesBackupInterface_Execute_Call) Return(_a0 error) *MockFilesBackupInterface_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesBackupInterface_Execute_Call) RunAndReturn(run func(*contexts.Context, clients.ClientInterface) error) *MockFilesBackupInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Setup provides a mock function with given fields: ctx, btiOpts
func (_m *MockFilesBackupInterface) Setup(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions) error {
	ret := _m.Called(ctx, btiOpts)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error); ok {
		r0 = rf(ctx, btiOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesBackupInterface_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockFilesBackupInterface_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions
func (_e *MockFilesBackupInterface_Expecter) Setup(ctx interface{}, btiOpts interface{}) *MockFilesBackupInterface_Setup_Call {
	return &MockFilesBackupInterface_Setup_Call{Call: _e.mock.On("Setup", ctx, btiOpts)}
}

func (_c *MockFilesBackupInterface_Setup_Call) Run(run func(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions)) *MockFilesBackupInterface_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(*backuptoolinstance.CreateBackupToolInstanceOptions))
	})
	return _c
}

func (_c *MockFilesBackupInterface_Setup_Call) Return(_a0 error) *MockFilesBackupInterface_Setup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesBackupInterface_Setup_Call) RunAndReturn(run func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error) *MockFilesBackupInterface_Setup_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: ctx
func (_m *MockFilesBackupInterface) Validate(ctx *contexts.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesBackupInterface_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockFilesBackupInterface_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockFilesBackupInterface_Expecter) Validate(ctx interface{}) *MockFilesBackupInterface_Validate_Call {
	return &MockFilesBackupInterface_Validate_Call{Call: _e.mock.On("Validate", ctx)}
}

func (_c *MockFilesBackupInterface_Validate_Call) Run(run func(ctx *contexts.Context)) *MockFilesBackupInterface_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockFilesBackupInterface_Validate_Call) Return(_a0 error) *MockFilesBackupInterface_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesBackupInterface_Validate_Call) RunAndReturn(run func(*contexts.Context) error) *MockFilesBackupInterface_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFilesBackupInterface creates a new instance of MockFilesBackupInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilesBackupInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilesBackupInterface {
	mock := &MockFilesBackupInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
