---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: zfs.csi.openebs.io
parameters:
  poolname: openebs-zpool
  fstype: zfs
---
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: openebs-zfs
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: zfs.csi.openebs.io
deletionPolicy: Delete
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed
spec:
  selfSigned: {}
---
# Approve all requested self-signed certs via the self-signed issuer
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: self-signed-issuer
spec:
  selector:
    issuerRef:
      group: cert-manager.io
      kind: Issuer
      name: self-signed
  allowed:
    isCA: true
    commonName: &all_value
      value: "*"
    dnsNames: &all_values
      values:
        - "*"
    emailAddresses: *all_values
    ipAddresses: *all_values
    subject:
      countries: *all_values
      localities: *all_values
      organizationalUnits: *all_values
      organizations: *all_values
      postalCodes: *all_values
      provinces: *all_values
      serialNumber: *all_value
      streetAddresses: *all_values
    uris: *all_values
    usages:
      - signing
      - digital signature
      - content commitment
      - key encipherment
      - key agreement
      - data encipherment
      - cert sign
      - crl sign
      - encipher only
      - decipher only
      - any
      - server auth
      - client auth
      - code signing
      - email protection
      - s/mime
      - ipsec end system
      - ipsec tunnel
      - ipsec user
      - timestamping
      - ocsp signing
      - microsoft sgc
      - netscape sgc
