---
master:
  data:
    type: persistentVolumeClaim
    size: 2Gi
    storageClass: standard
  affinity: ""
  volumeSizeLimitMB: 256
volume:
  dataDirs:
    - name: data
      type: persistentVolumeClaim
      size: 2Gi
      storageClass: standard
      maxVolumes: 0
  affinity: ""
filer:
  enablePVC: true
  storage: 2Gi
  storageClass: standard
  data:
    type: persistentVolumeClaim
    size: 2Gi
    storageClass: standard
  affinity: ""
  s3:
    enabled: true
    enableAuth: true
s3:
  enabled: true
  logs:
    type: emptyDir
  enableAuth: true
