// Code generated by mockery v2.51.0. DO NOT EDIT.

package remote

import (
	clients "github.com/solidDoWant/backup-tool/pkg/grpc/clients"
	backuptoolinstance "github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/backuptoolinstance"

	contexts "github.com/solidDoWant/backup-tool/pkg/contexts"

	mock "github.com/stretchr/testify/mock"
)

// MockCleanupAction is an autogenerated mock type for the CleanupAction type
type MockCleanupAction struct {
	mock.Mock
}

type MockCleanupAction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCleanupAction) EXPECT() *MockCleanupAction_Expecter {
	return &MockCleanupAction_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with given fields: ctx
func (_m *MockCleanupAction) Cleanup(ctx *contexts.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCleanupAction_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockCleanupAction_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockCleanupAction_Expecter) Cleanup(ctx interface{}) *MockCleanupAction_Cleanup_Call {
	return &MockCleanupAction_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx)}
}

func (_c *MockCleanupAction_Cleanup_Call) Run(run func(ctx *contexts.Context)) *MockCleanupAction_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockCleanupAction_Cleanup_Call) Return(_a0 error) *MockCleanupAction_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCleanupAction_Cleanup_Call) RunAndReturn(run func(*contexts.Context) error) *MockCleanupAction_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: ctx, backupToolClient
func (_m *MockCleanupAction) Execute(ctx *contexts.Context, backupToolClient clients.ClientInterface) error {
	ret := _m.Called(ctx, backupToolClient)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, clients.ClientInterface) error); ok {
		r0 = rf(ctx, backupToolClient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCleanupAction_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCleanupAction_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - backupToolClient clients.ClientInterface
func (_e *MockCleanupAction_Expecter) Execute(ctx interface{}, backupToolClient interface{}) *MockCleanupAction_Execute_Call {
	return &MockCleanupAction_Execute_Call{Call: _e.mock.On("Execute", ctx, backupToolClient)}
}

func (_c *MockCleanupAction_Execute_Call) Run(run func(ctx *contexts.Context, backupToolClient clients.ClientInterface)) *MockCleanupAction_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(clients.ClientInterface))
	})
	return _c
}

func (_c *MockCleanupAction_Execute_Call) Return(_a0 error) *MockCleanupAction_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCleanupAction_Execute_Call) RunAndReturn(run func(*contexts.Context, clients.ClientInterface) error) *MockCleanupAction_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Setup provides a mock function with given fields: ctx, btiOpts
func (_m *MockCleanupAction) Setup(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions) error {
	ret := _m.Called(ctx, btiOpts)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error); ok {
		r0 = rf(ctx, btiOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCleanupAction_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockCleanupAction_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions
func (_e *MockCleanupAction_Expecter) Setup(ctx interface{}, btiOpts interface{}) *MockCleanupAction_Setup_Call {
	return &MockCleanupAction_Setup_Call{Call: _e.mock.On("Setup", ctx, btiOpts)}
}

func (_c *MockCleanupAction_Setup_Call) Run(run func(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions)) *MockCleanupAction_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(*backuptoolinstance.CreateBackupToolInstanceOptions))
	})
	return _c
}

func (_c *MockCleanupAction_Setup_Call) Return(_a0 error) *MockCleanupAction_Setup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCleanupAction_Setup_Call) RunAndReturn(run func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error) *MockCleanupAction_Setup_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: ctx
func (_m *MockCleanupAction) Validate(ctx *contexts.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCleanupAction_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockCleanupAction_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockCleanupAction_Expecter) Validate(ctx interface{}) *MockCleanupAction_Validate_Call {
	return &MockCleanupAction_Validate_Call{Call: _e.mock.On("Validate", ctx)}
}

func (_c *MockCleanupAction_Validate_Call) Run(run func(ctx *contexts.Context)) *MockCleanupAction_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockCleanupAction_Validate_Call) Return(_a0 error) *MockCleanupAction_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCleanupAction_Validate_Call) RunAndReturn(run func(*contexts.Context) error) *MockCleanupAction_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCleanupAction creates a new instance of MockCleanupAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCleanupAction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCleanupAction {
	mock := &MockCleanupAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
