// Code generated by mockery v2.53.6. DO NOT EDIT.

package restore

import (
	clients "github.com/solidDoWant/backup-tool/pkg/grpc/clients"
	backuptoolinstance "github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/backuptoolinstance"

	contexts "github.com/solidDoWant/backup-tool/pkg/contexts"

	kubecluster "github.com/solidDoWant/backup-tool/pkg/kubecluster"

	mock "github.com/stretchr/testify/mock"
)

// MockFilesRestoreInterface is an autogenerated mock type for the FilesRestoreInterface type
type MockFilesRestoreInterface struct {
	mock.Mock
}

type MockFilesRestoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilesRestoreInterface) EXPECT() *MockFilesRestoreInterface_Expecter {
	return &MockFilesRestoreInterface_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function with given fields: kubeClusterClient, namespace, targetPVCName, drVolName, backupDirRelPath, opts
func (_m *MockFilesRestoreInterface) Configure(kubeClusterClient kubecluster.ClientInterface, namespace string, targetPVCName string, drVolName string, backupDirRelPath string, opts FilesRestoreOptions) error {
	ret := _m.Called(kubeClusterClient, namespace, targetPVCName, drVolName, backupDirRelPath, opts)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(kubecluster.ClientInterface, string, string, string, string, FilesRestoreOptions) error); ok {
		r0 = rf(kubeClusterClient, namespace, targetPVCName, drVolName, backupDirRelPath, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesRestoreInterface_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockFilesRestoreInterface_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - kubeClusterClient kubecluster.ClientInterface
//   - namespace string
//   - targetPVCName string
//   - drVolName string
//   - backupDirRelPath string
//   - opts FilesRestoreOptions
func (_e *MockFilesRestoreInterface_Expecter) Configure(kubeClusterClient interface{}, namespace interface{}, targetPVCName interface{}, drVolName interface{}, backupDirRelPath interface{}, opts interface{}) *MockFilesRestoreInterface_Configure_Call {
	return &MockFilesRestoreInterface_Configure_Call{Call: _e.mock.On("Configure", kubeClusterClient, namespace, targetPVCName, drVolName, backupDirRelPath, opts)}
}

func (_c *MockFilesRestoreInterface_Configure_Call) Run(run func(kubeClusterClient kubecluster.ClientInterface, namespace string, targetPVCName string, drVolName string, backupDirRelPath string, opts FilesRestoreOptions)) *MockFilesRestoreInterface_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(kubecluster.ClientInterface), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(FilesRestoreOptions))
	})
	return _c
}

func (_c *MockFilesRestoreInterface_Configure_Call) Return(_a0 error) *MockFilesRestoreInterface_Configure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesRestoreInterface_Configure_Call) RunAndReturn(run func(kubecluster.ClientInterface, string, string, string, string, FilesRestoreOptions) error) *MockFilesRestoreInterface_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: ctx, backupToolClient
func (_m *MockFilesRestoreInterface) Execute(ctx *contexts.Context, backupToolClient clients.ClientInterface) error {
	ret := _m.Called(ctx, backupToolClient)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, clients.ClientInterface) error); ok {
		r0 = rf(ctx, backupToolClient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesRestoreInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFilesRestoreInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - backupToolClient clients.ClientInterface
func (_e *MockFilesRestoreInterface_Expecter) Execute(ctx interface{}, backupToolClient interface{}) *MockFilesRestoreInterface_Execute_Call {
	return &MockFilesRestoreInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, backupToolClient)}
}

func (_c *MockFilesRestoreInterface_Execute_Call) Run(run func(ctx *contexts.Context, backupToolClient clients.ClientInterface)) *MockFilesRestoreInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(clients.ClientInterface))
	})
	return _c
}

func (_c *MockFilesRestoreInterface_Execute_Call) Return(_a0 error) *MockFilesRestoreInterface_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesRestoreInterface_Execute_Call) RunAndReturn(run func(*contexts.Context, clients.ClientInterface) error) *MockFilesRestoreInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Setup provides a mock function with given fields: ctx, btiOpts
func (_m *MockFilesRestoreInterface) Setup(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions) error {
	ret := _m.Called(ctx, btiOpts)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error); ok {
		r0 = rf(ctx, btiOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesRestoreInterface_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockFilesRestoreInterface_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions
func (_e *MockFilesRestoreInterface_Expecter) Setup(ctx interface{}, btiOpts interface{}) *MockFilesRestoreInterface_Setup_Call {
	return &MockFilesRestoreInterface_Setup_Call{Call: _e.mock.On("Setup", ctx, btiOpts)}
}

func (_c *MockFilesRestoreInterface_Setup_Call) Run(run func(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions)) *MockFilesRestoreInterface_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(*backuptoolinstance.CreateBackupToolInstanceOptions))
	})
	return _c
}

func (_c *MockFilesRestoreInterface_Setup_Call) Return(_a0 error) *MockFilesRestoreInterface_Setup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesRestoreInterface_Setup_Call) RunAndReturn(run func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error) *MockFilesRestoreInterface_Setup_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: ctx
func (_m *MockFilesRestoreInterface) Validate(ctx *contexts.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilesRestoreInterface_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockFilesRestoreInterface_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockFilesRestoreInterface_Expecter) Validate(ctx interface{}) *MockFilesRestoreInterface_Validate_Call {
	return &MockFilesRestoreInterface_Validate_Call{Call: _e.mock.On("Validate", ctx)}
}

func (_c *MockFilesRestoreInterface_Validate_Call) Run(run func(ctx *contexts.Context)) *MockFilesRestoreInterface_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockFilesRestoreInterface_Validate_Call) Return(_a0 error) *MockFilesRestoreInterface_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilesRestoreInterface_Validate_Call) RunAndReturn(run func(*contexts.Context) error) *MockFilesRestoreInterface_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFilesRestoreInterface creates a new instance of MockFilesRestoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilesRestoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilesRestoreInterface {
	mock := &MockFilesRestoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
