// Code generated by mockery v2.51.0. DO NOT EDIT.

package backuptoolinstance

import (
	contexts "github.com/solidDoWant/backup-tool/pkg/contexts"
	mock "github.com/stretchr/testify/mock"
)

// MockProviderInterface is an autogenerated mock type for the ProviderInterface type
type MockProviderInterface struct {
	mock.Mock
}

type MockProviderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderInterface) EXPECT() *MockProviderInterface_Expecter {
	return &MockProviderInterface_Expecter{mock: &_m.Mock}
}

// CreateBackupToolInstance provides a mock function with given fields: ctx, namespace, instance, opts
func (_m *MockProviderInterface) CreateBackupToolInstance(ctx *contexts.Context, namespace string, instance string, opts CreateBackupToolInstanceOptions) (BackupToolInstanceInterface, error) {
	ret := _m.Called(ctx, namespace, instance, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackupToolInstance")
	}

	var r0 BackupToolInstanceInterface
	var r1 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, CreateBackupToolInstanceOptions) (BackupToolInstanceInterface, error)); ok {
		return rf(ctx, namespace, instance, opts)
	}
	if rf, ok := ret.Get(0).(func(*contexts.Context, string, string, CreateBackupToolInstanceOptions) BackupToolInstanceInterface); ok {
		r0 = rf(ctx, namespace, instance, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(BackupToolInstanceInterface)
		}
	}

	if rf, ok := ret.Get(1).(func(*contexts.Context, string, string, CreateBackupToolInstanceOptions) error); ok {
		r1 = rf(ctx, namespace, instance, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderInterface_CreateBackupToolInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBackupToolInstance'
type MockProviderInterface_CreateBackupToolInstance_Call struct {
	*mock.Call
}

// CreateBackupToolInstance is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - namespace string
//   - instance string
//   - opts CreateBackupToolInstanceOptions
func (_e *MockProviderInterface_Expecter) CreateBackupToolInstance(ctx interface{}, namespace interface{}, instance interface{}, opts interface{}) *MockProviderInterface_CreateBackupToolInstance_Call {
	return &MockProviderInterface_CreateBackupToolInstance_Call{Call: _e.mock.On("CreateBackupToolInstance", ctx, namespace, instance, opts)}
}

func (_c *MockProviderInterface_CreateBackupToolInstance_Call) Run(run func(ctx *contexts.Context, namespace string, instance string, opts CreateBackupToolInstanceOptions)) *MockProviderInterface_CreateBackupToolInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(string), args[2].(string), args[3].(CreateBackupToolInstanceOptions))
	})
	return _c
}

func (_c *MockProviderInterface_CreateBackupToolInstance_Call) Return(btInstance BackupToolInstanceInterface, err error) *MockProviderInterface_CreateBackupToolInstance_Call {
	_c.Call.Return(btInstance, err)
	return _c
}

func (_c *MockProviderInterface_CreateBackupToolInstance_Call) RunAndReturn(run func(*contexts.Context, string, string, CreateBackupToolInstanceOptions) (BackupToolInstanceInterface, error)) *MockProviderInterface_CreateBackupToolInstance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProviderInterface creates a new instance of MockProviderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderInterface {
	mock := &MockProviderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
