---
helmDefaults:
  cleanupOnFail: true
  wait: true
  waitForJobs: true
  createNamespace: false
  historyMax: 1
  timeout: 600

repositories:
  - name: bjw-s-charts
    url: https://bjw-s-labs.github.io/helm-charts

releases:
  - name: teleport-restore-client-cas
    chart: bjw-s-charts/app-template
    version: 5.0.1
    atomic: true
    values:
      - ./client-cas.values.yaml
  - name: teleport-restore-backend
    chart: bjw-s-charts/app-template
    version: 5.0.1
    atomic: true
    needs:
      - teleport-restore-client-cas
    values:
      - ./backend.values.yaml
