// Code generated by mockery v2.51.0. DO NOT EDIT.

package s3sync

import (
	clients "github.com/solidDoWant/backup-tool/pkg/grpc/clients"
	backuptoolinstance "github.com/solidDoWant/backup-tool/pkg/kubecluster/composite/backuptoolinstance"

	contexts "github.com/solidDoWant/backup-tool/pkg/contexts"

	kubecluster "github.com/solidDoWant/backup-tool/pkg/kubecluster"

	mock "github.com/stretchr/testify/mock"

	s3 "github.com/solidDoWant/backup-tool/pkg/s3"
)

// MockS3SyncInterface is an autogenerated mock type for the S3SyncInterface type
type MockS3SyncInterface struct {
	mock.Mock
}

type MockS3SyncInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3SyncInterface) EXPECT() *MockS3SyncInterface_Expecter {
	return &MockS3SyncInterface_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function with given fields: kubeClusterClient, namespace, drVolName, backupDirRelPath, s3Path, credentials, direction, opts
func (_m *MockS3SyncInterface) Configure(kubeClusterClient kubecluster.ClientInterface, namespace string, drVolName string, backupDirRelPath string, s3Path string, credentials s3.CredentialsInterface, direction Direction, opts S3SyncOptions) error {
	ret := _m.Called(kubeClusterClient, namespace, drVolName, backupDirRelPath, s3Path, credentials, direction, opts)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(kubecluster.ClientInterface, string, string, string, string, s3.CredentialsInterface, Direction, S3SyncOptions) error); ok {
		r0 = rf(kubeClusterClient, namespace, drVolName, backupDirRelPath, s3Path, credentials, direction, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockS3SyncInterface_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockS3SyncInterface_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - kubeClusterClient kubecluster.ClientInterface
//   - namespace string
//   - drVolName string
//   - backupDirRelPath string
//   - s3Path string
//   - credentials s3.CredentialsInterface
//   - direction Direction
//   - opts S3SyncOptions
func (_e *MockS3SyncInterface_Expecter) Configure(kubeClusterClient interface{}, namespace interface{}, drVolName interface{}, backupDirRelPath interface{}, s3Path interface{}, credentials interface{}, direction interface{}, opts interface{}) *MockS3SyncInterface_Configure_Call {
	return &MockS3SyncInterface_Configure_Call{Call: _e.mock.On("Configure", kubeClusterClient, namespace, drVolName, backupDirRelPath, s3Path, credentials, direction, opts)}
}

func (_c *MockS3SyncInterface_Configure_Call) Run(run func(kubeClusterClient kubecluster.ClientInterface, namespace string, drVolName string, backupDirRelPath string, s3Path string, credentials s3.CredentialsInterface, direction Direction, opts S3SyncOptions)) *MockS3SyncInterface_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(kubecluster.ClientInterface), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(s3.CredentialsInterface), args[6].(Direction), args[7].(S3SyncOptions))
	})
	return _c
}

func (_c *MockS3SyncInterface_Configure_Call) Return(_a0 error) *MockS3SyncInterface_Configure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockS3SyncInterface_Configure_Call) RunAndReturn(run func(kubecluster.ClientInterface, string, string, string, string, s3.CredentialsInterface, Direction, S3SyncOptions) error) *MockS3SyncInterface_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: ctx, backupToolClient
func (_m *MockS3SyncInterface) Execute(ctx *contexts.Context, backupToolClient clients.ClientInterface) error {
	ret := _m.Called(ctx, backupToolClient)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, clients.ClientInterface) error); ok {
		r0 = rf(ctx, backupToolClient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockS3SyncInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockS3SyncInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - backupToolClient clients.ClientInterface
func (_e *MockS3SyncInterface_Expecter) Execute(ctx interface{}, backupToolClient interface{}) *MockS3SyncInterface_Execute_Call {
	return &MockS3SyncInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, backupToolClient)}
}

func (_c *MockS3SyncInterface_Execute_Call) Run(run func(ctx *contexts.Context, backupToolClient clients.ClientInterface)) *MockS3SyncInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(clients.ClientInterface))
	})
	return _c
}

func (_c *MockS3SyncInterface_Execute_Call) Return(_a0 error) *MockS3SyncInterface_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockS3SyncInterface_Execute_Call) RunAndReturn(run func(*contexts.Context, clients.ClientInterface) error) *MockS3SyncInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Setup provides a mock function with given fields: ctx, btiOpts
func (_m *MockS3SyncInterface) Setup(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions) error {
	ret := _m.Called(ctx, btiOpts)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error); ok {
		r0 = rf(ctx, btiOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockS3SyncInterface_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockS3SyncInterface_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - ctx *contexts.Context
//   - btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions
func (_e *MockS3SyncInterface_Expecter) Setup(ctx interface{}, btiOpts interface{}) *MockS3SyncInterface_Setup_Call {
	return &MockS3SyncInterface_Setup_Call{Call: _e.mock.On("Setup", ctx, btiOpts)}
}

func (_c *MockS3SyncInterface_Setup_Call) Run(run func(ctx *contexts.Context, btiOpts *backuptoolinstance.CreateBackupToolInstanceOptions)) *MockS3SyncInterface_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context), args[1].(*backuptoolinstance.CreateBackupToolInstanceOptions))
	})
	return _c
}

func (_c *MockS3SyncInterface_Setup_Call) Return(_a0 error) *MockS3SyncInterface_Setup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockS3SyncInterface_Setup_Call) RunAndReturn(run func(*contexts.Context, *backuptoolinstance.CreateBackupToolInstanceOptions) error) *MockS3SyncInterface_Setup_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: ctx
func (_m *MockS3SyncInterface) Validate(ctx *contexts.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*contexts.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockS3SyncInterface_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockS3SyncInterface_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx *contexts.Context
func (_e *MockS3SyncInterface_Expecter) Validate(ctx interface{}) *MockS3SyncInterface_Validate_Call {
	return &MockS3SyncInterface_Validate_Call{Call: _e.mock.On("Validate", ctx)}
}

func (_c *MockS3SyncInterface_Validate_Call) Run(run func(ctx *contexts.Context)) *MockS3SyncInterface_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*contexts.Context))
	})
	return _c
}

func (_c *MockS3SyncInterface_Validate_Call) Return(_a0 error) *MockS3SyncInterface_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockS3SyncInterface_Validate_Call) RunAndReturn(run func(*contexts.Context) error) *MockS3SyncInterface_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockS3SyncInterface creates a new instance of MockS3SyncInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3SyncInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3SyncInterface {
	mock := &MockS3SyncInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
